const languages = {
  HTML: {
    easy: [
      { q: "Quelle balise utilise-t-on pour creer un lien hypertexte ?", a: "<a>", b: "<link>", c: "<href>", d: "<url>", ans: "a" },
      { q: "Quelle balise definit le titre d'une page web ?", a: "<head>", b: "<title>", c: "<meta>", d: "<header>", ans: "b" },
      { q: "Quelle balise insere une image ?", a: "<image>", b: "<img>", c: "<pic>", d: "<src>", ans: "b" },
      { q: "Quelle balise cree un paragraphe ?", a: "<p>", b: "<para>", c: "<text>", d: "<pg>", ans: "a" },
      { q: "Quelle balise rend un texte en gras ?", a: "<bold>", b: "<b>", c: "<strong>", d: "b et c", ans: "d" },
      { q: "Quel attribut definit l'URL d'un lien ?", a: "src", b: "href", c: "link", d: "url", ans: "b" },
      { q: "Quelle balise insere un saut de ligne ?", a: "<break>", b: "<lb>", c: "<br>", d: "<newline>", ans: "c" },
      { q: "Quelle balise cree une liste non ordonnee ?", a: "<ul>", b: "<ol>", c: "<li>", d: "<list>", ans: "a" },
      { q: "Quel est le bon DOCTYPE pour HTML5 ?", a: "<!DOCTYPE html>", b: "<!DOCTYPE HTML5>", c: "<doctype html5>", d: "<DOCTYPE html>", ans: "a" },
      { q: "Quelle balise definit un en-tete de niveau 1 ?", a: "<h1>", b: "<header>", c: "<head1>", d: "<title>", ans: "a" },
    ],
    medium: [
      { q: "Quel attribut specifie une image de remplacement ?", a: "alt", b: "title", c: "src", d: "desc", ans: "a" },
      { q: "Quelle balise definit un tableau ?", a: "<table>", b: "<grid>", c: "<tab>", d: "<data>", ans: "a" },
      { q: "Quel attribut ouvre un lien dans un nouvel onglet ?", a: "new-tab", b: "target=_blank", c: "open=new", d: "blank=true", ans: "b" },
      { q: "Quelle balise definit un bloc de code ?", a: "<code>", b: "<pre>", c: "<program>", d: "a et b", ans: "d" },
      { q: "Quel attribut definit l'identifiant unique d'un element ?", a: "class", b: "id", c: "name", d: "key", ans: "b" },
      { q: "Quelle balise cree un champ de saisie ?", a: "<field>", b: "<input>", c: "<text>", d: "<form-field>", ans: "b" },
      { q: "Quel attribut rend un champ obligatoire ?", a: "needed", b: "required", c: "mandatory", d: "obligatory", ans: "b" },
      { q: "Quelle balise definit un footer ?", a: "<bottom>", b: "<footer>", c: "<end>", d: "<foot>", ans: "b" },
      { q: "Combien de niveaux de titres HTML existe-t-il ?", a: "4", b: "5", c: "6", d: "8", ans: "c" },
      { q: "Quelle balise groupe des elements de formulaire ?", a: "<form-group>", b: "<fieldset>", c: "<group>", d: "<form>", ans: "b" },
    ],
    hard: [
      { q: "Quel est le role de l'attribut 'lang' sur <html> ?", a: "Definir le charset", b: "Indiquer la langue", c: "Gerer les localisations", d: "Traduire le contenu", ans: "b" },
      { q: "Quelle balise audio est recommandee en HTML5 ?", a: "<sound>", b: "<music>", c: "<audio>", d: "<media>", ans: "c" },
      { q: "Quel attribut active la validation d'un formulaire ?", a: "validate", b: "novalidate (inverse)", c: "check", d: "verify", ans: "b" },
      { q: "Quelle API Web permet le stockage local ?", a: "LocalStore", b: "localStorage", c: "WebStorage", d: "b et c", ans: "d" },
      { q: "Quelle balise definit une section autonome ?", a: "<div>", b: "<section>", c: "<part>", d: "<block>", ans: "b" },
      { q: "Quel est le schema MIME d'HTML5 ?", a: "text/html", b: "application/html", c: "text/xml", d: "application/xml", ans: "a" },
      { q: "Quelle balise affiche une video embarquee ?", a: "<video>", b: "<movie>", c: "<embed>", d: "<media>", ans: "a" },
      { q: "Quel attribut definit le charset d'un document ?", a: "encoding", b: "charset", c: "character-set", d: "char", ans: "b" },
      { q: "Quelle balise represente une legende dans un tableau ?", a: "<caption>", b: "<legend>", c: "<title>", d: "<desc>", ans: "a" },
      { q: "Quel attribut specifie le type d'un input ?", a: "type", b: "kind", c: "format", d: "mode", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce que le Shadow DOM en HTML5 ?", a: "Un mode sombre", b: "Un DOM encapsule", c: "Un cache", d: "Un service worker", ans: "b" },
      { q: "Quel attribut definit la priorite de chargement d'un script ?", a: "priority", b: "importance", c: "fetchpriority", d: "weight", ans: "c" },
      { q: "Qu'est-ce que le Lazy Loading en HTML ?", a: "Chargement differe des images", b: "Un type de cache", c: "Une animation", d: "Un script async", ans: "a" },
      { q: "Quel attribut definit les sources responsive d'une image ?", a: "srcset", b: "responsive", c: "imagesrcset", d: "a et c", ans: "d" },
      { q: "Quelle API permet la communication entre onglets ?", a: "BroadcastChannel", b: "CrossTab", c: "TabChannel", d: "SharedWorker", ans: "a" },
      { q: "Quel attribut definit les dimensions intrinseques d'une image ?", a: "size", b: "width/height", c: "dimensions", d: "intrinsic", ans: "b" },
      { q: "Qu'est-ce qu'un Web Component ?", a: "Un framework", b: "Un composant encapsule avec Shadow DOM", c: "Un plugin", d: "Un service", ans: "b" },
      { q: "Quel attribut empêche l'exécution d'un script ?", a: "disabled", b: "noscript", c: "defer", d: "integrity", ans: "a" },
      { q: "Quelle API permet la detection du network ?", a: "NetworkInformation", b: "Navigator.connection", c: "NetInfo", d: "a et b", ans: "d" },
      { q: "Quel attribut definit l'integrité d'une ressource ?", a: "security", b: "integrity", c: "hash", d: "checksum", ans: "b" },
    ],
    master: [
      { q: "Qu'est-ce que le Content Security Policy (CSP) ?", a: "Un type d'encryption", b: "Une politique de securite des contenus", c: "Un pare-feu", d: "Un protocole", ans: "b" },
      { q: "Quel attribut definit le referrer policy ?", a: "referer-policy", b: "referrerpolicy", c: "referrer", d: "origin-policy", ans: "b" },
      { q: "Qu'est-ce que le Preload Scanner dans les navigateurs ?", a: "Un antivirus", b: "Un scanner qui charge les ressources critiques en avance", c: "Un parser CSS", d: "Un validateur", ans: "b" },
      { q: "Quel attribut specifie les credentiales pour les images cross-origin ?", a: "credentials", b: "crossorigin", c: "access", d: "auth", ans: "b" },
      { q: "Qu'est-ce que le History API ?", a: "Un historique de navigation", b: "Une API pour manipuler l'historique du navigateur", c: "Un cache", d: "Un cookie", ans: "b" },
      { q: "Quel attribut definit la politique de cache des active embeddings ?", a: "cache", b: "credentialless", c: "store", d: "persist", ans: "b" },
      { q: "Qu'est-ce que le speculation rules API ?", a: "Des regles SEO", b: "Des regles de prefetch/prerender speculatif", c: "Des regles de cache", d: "Des regles CORS", ans: "b" },
      { q: "Quel attribut definit la taille d'un element en CSS via HTML ?", a: "style", b: "width/height (presentational hints)", c: "class", d: "data-size", ans: "b" },
      { q: "Qu'est-ce que le declarative shadow DOM ?", a: "Un shadow DOM serveur-side rendu", b: "Un shadow DOM cache", c: "Un shadow DOM async", d: "Un shadow DOM dynamique", ans: "a" },
      { q: "Quel attribut empeche le clonage d'un champ ?", a: "noclone", b: "autocomplete=off", c: "readonly", d: "immutable", ans: "b" },
    ],
  },
  CSS: {
    easy: [
      { q: "Quelle propriete change la couleur de fond ?", a: "color", b: "background-color", c: "bg-color", d: "fill", ans: "b" },
      { q: "Quelle propriete definit la taille du texte ?", a: "text-size", b: "font-size", c: "text-style", d: "size", ans: "b" },
      { q: "Quelle propriete ajoute un espace interne ?", a: "margin", b: "spacing", c: "padding", d: "gap", ans: "c" },
      { q: "Quelle propriete centre un element horizontalement ?", a: "center", b: "margin: auto", c: "align: center", d: "text-align: center", ans: "b" },
      { q: "Quelle propriete rend le texte en gras ?", a: "text-weight: bold", b: "font-weight: bold", c: "bold: true", d: "text: bold", ans: "b" },
      { q: "Quel selecteur cible tous les elements <p> ?", a: ".p", b: "#p", c: "p", d: "*p", ans: "c" },
      { q: "Quelle propriete change la police ?", a: "font-family", b: "font-type", c: "typeface", d: "font-style", ans: "a" },
      { q: "Quelle propriete ajoute une ombre ?", a: "shadow", b: "box-shadow", c: "text-shadow", d: "b et c", ans: "d" },
      { q: "Quel est le model box par defaut ?", a: "content-box", b: "border-box", c: "padding-box", d: "margin-box", ans: "a" },
      { q: "Quelle propriete definit la hauteur ?", a: "height", b: "h", c: "hauteur", d: "size-h", ans: "a" },
    ],
    medium: [
      { q: "Quelle propriete utilise Flexbox ?", a: "display: flex", b: "position: flex", c: "layout: flex", d: "flex: true", ans: "a" },
      { q: "Quelle propriete definit l'axe principal dans Flexbox ?", a: "flex-direction", b: "flex-axis", c: "direction", d: "orient", ans: "a" },
      { q: "Quel selecteur cible une classe ?", a: "#", b: ".", c: "@", d: "/", ans: "b" },
      { q: "Quelle propriete rend un element invisible mais preserve l'espace ?", a: "display: none", b: "visibility: hidden", c: "opacity: 0", d: "hidden: true", ans: "b" },
      { q: "Quelle propriete positionne un element avec reference a son parent ?", a: "absolute", b: "relative", c: "fixed", d: "sticky", ans: "b" },
      { q: "Quelle propriete definit le rayon d'arrondi ?", a: "round", b: "border-radius", c: "corner-radius", d: "radius", ans: "b" },
      { q: "Quelle propriete gere la transparence ?", a: "transparency", b: "alpha", c: "opacity", d: "fade", ans: "c" },
      { q: "Quelle propriete CSS anime un element ?", a: "animation", b: "transition", c: "a et b", d: "neither", ans: "c" },
      { q: "Quel framework CSS est le plus populaire ?", a: "Bootstrap", b: "Tailwind CSS", c: "Bulma", d: "Foundation", ans: "b" },
      { q: "Quelle propriete definit l'espace entre les elements enfants d'un flex container ?", a: "flex-gap", b: "gap", c: "spacing", d: "margin-between", ans: "b" },
    ],
    hard: [
      { q: "Qu'est-ce que CSS Grid ?", a: "Un systeme de layout bidimensionnel", b: "Un framework JS", c: "Un type de police", d: "Un protocole", ans: "a" },
      { q: "Quelle pseudo-classe cible le premier enfant ?", a: ":first-child", b: ":first", c: ":nth-child(1)", d: "a et c", ans: "d" },
      { q: "Quelle propriete definit l'ordre d'un element dans Grid ?", a: "order", b: "grid-order", c: "position", d: "stack", ans: "a" },
      { q: "Qu'est-ce que le BEM en CSS ?", a: "Block Element Modifier", b: "Best Element Model", c: "Basic Element Method", d: "Block Encapsulation Model", ans: "a" },
      { q: "Quelle propriete crée un gradient ?", a: "background: gradient()", b: "linear-gradient()", c: "gradient: linear", d: "bg-gradient", ans: "b" },
      { q: "Qu'est-ce que le container queries ?", a: "Des media queries pour conteneurs", b: "Des requetes de base de donnees", c: "Des animations", d: "Des variables", ans: "a" },
      { q: "Quelle propriete definit le z-index ?", a: "z-index", b: "stacking-order", c: "layer", d: "z-order", ans: "a" },
      { q: "Qu'est-ce que CSS custom properties (variables) ?", a: "Des variables CSS avec --", b: "Des classes custom", c: "Des composants", d: "Des mixins", ans: "a" },
      { q: "Quelle propriete adapte un element a l'impression ?", a: "@media print", b: "print-color-adjust", c: "media: print", d: "a et b", ans: "d" },
      { q: "Quel role a la propriete 'clip-path' ?", a: "Decoupe un element selon une forme", b: "Cache un element", c: "Rogne une image", d: "Ajoute une bordure", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce que le Subgrid en CSS ?", a: "Un alignement de grille imbrique", b: "Un type de grille", c: "Un media query", d: "Un pseudo-element", ans: "a" },
      { q: "Quelle propriete definit le comportement du texte qui depasse ?", a: "text-overflow", b: "overflow-wrap", c: "word-break", d: "toutes", ans: "d" },
      { q: "Qu'est-ce que :has() en CSS ?", a: "Un selecteur parent conditionnel", b: "Un pseudo-element", c: "Une animation", d: "Une media query", ans: "a" },
      { q: "Quel role joue 'will-change' ?", a: "Optimise les performances d'animation", b: "Change le comportement", c: "Detecte les changements", d: "Ajoute des transitions", ans: "a" },
      { q: "Qu'est-ce que le color-mix() en CSS ?", a: "Melange deux couleurs", b: "Convertit les couleurs", c: "Genere des palettes", d: "Filtre les couleurs", ans: "a" },
      { q: "Quelle propriete controle l'anti-aliasing du texte ?", a: "font-smoothing", b: "-webkit-font-smoothing", c: "text-rendering", d: "toutes", ans: "d" },
      { q: "Qu'est-ce que le scroll-driven animations ?", a: "Animations liees au scroll", b: "Infinite scroll", c: "Lazy loading", d: "Smooth scroll", ans: "a" },
      { q: "Quel role a 'accent-color' ?", a: "Personnalise la couleur des elements de form", b: "Change la couleur du texte", c: "Ajoute un accent", d: "Modifie le theme", ans: "a" },
      { q: "Qu'est-ce que CSS Nesting natif ?", a: "Imbrication sans preprocesseur", b: "Des animations imbriquees", c: "Des grilles imbriquees",d: "Des media queries imbriquees", ans: "a" },
      { q: "Quelle propriete definit le comportement de mise en page d'impression ?", a: "page-break-before", b: "break-before", c: "pagination", d: "a et b", ans: "d" },
    ],
    master: [
      { q: "Qu'est-ce que le View Transitions API en CSS ?", a: "Animations de transition entre vues/pages", b: "Un type de media query", c: "Un selecteur",d: "Un framework CSS", ans: "a" },
      { q: "Quel role a 'content-visibility' ?", a: "Cache le rendu d'elements hors-viewport", b: "Change le contenu", c: "Ajoute du texte",d: "Masque un element", ans: "a" },
      { q: "Qu'est-ce que le :user-valid en CSS ?", a: "Valide les champs de formulaire", b: "Verifie l'accessibilite",c: "Detecte le theme utilisateur",d: "Gere les permissions", ans: "a" },
      { q: "Quelle propriete definit le point de rupture d'un flex item ?", a: "break-inside", b: "flex-shrink", c: "min-width",d: "toutes", ans: "d" },
      { q: "Qu'est-ce que le CSS @layer ?", a: "Definit l'ordre de priorite des cascade layers",b: "Un type d'animation",c: "Un media query",d: "Un pseudo-element", ans: "a" },
      { q: "Quel role a 'color-scheme' ?", a: "Indique les schemas de couleur supportes",b: "Change la police",c: "Modifie le layout",d: "Gere les themes", ans: "a" },
      { q: "Qu'est-ce que 'interpolate-size' en CSS ?", a: "Interpole les tailles pour animations fluides",b: "Redefinit la taille des polices",c: "Change les dimensions",d: "Ajoute du padding", ans: "a" },
      { q: "Quelle propriete definit la taille d'un conteneur de grille ?", a: "grid-template-rows", b: "grid-auto-rows", c: "grid-row-gap",d: "a et b", ans: "d" },
      { q: "Qu'est-ce que le @scope en CSS ?", a: "Limite les styles a un sous-ensemble du DOM",b: "Un selecteur global",c: "Un type d'animation",d: "Un media query", ans: "a" },
      { q: "Quel role a 'field-sizing' ?", a: "Redimensionne automatiquement un champ de formulaire",b: "Change la taille du texte",c: "Modifie le layout",d: "Gere les bordures", ans: "a" },
    ],
  },
  JavaScript: {
    easy: [
      { q: "Comment declare-t-on une variable en JS moderne ?", a: "var", b: "let", c: "variable", d: "define", ans: "b" },
      { q: "Quel operateur compare la valeur ET le type ?", a: "==", b: "===", c: "!=", d: "<>", ans: "b" },
      { q: "Comment affiche-t-on dans la console ?", a: "print()", b: "log()", c: "console.log()", d: "echo()", ans: "c" },
      { q: "Quel mot-cle cree une fonction ?", a: "func", b: "function", c: "def", d: "fn", ans: "b" },
      { q: "Comment ajoute-t-on un element a un tableau ?", a: "add()", b: "push()", c: "insert()", d: "append()", ans: "b" },
      { q: "Quel type contient du texte en JS ?", a: "String", b: "Text", c: "Char", d: "Word", ans: "a" },
      { q: "Comment ecrit-on un commentaire sur une ligne ?", a: "//", b: "#", c: "--", d: "/*", ans: "a" },
      { q: "Quel operateur logique ET ?", a: "||", b: "&&", c: "!", d: "&", ans: "b" },
      { q: "Que retourne typeof null ?", a: 'null', b: '"object"', c: '"undefined"', d: '"boolean"', ans: "b" },
      { q: "Comment declare-t-on une constante ?", a: "const", b: "let", c: "var", d: "static", ans: "a" },
    ],
    medium: [
      { q: "Qu'est-ce qu'un closure en JS ?", a: "Une fonction qui capture des variables de sa portee", b: "Un type de boucle", c: "Un objet", d: "Un prototype", ans: "a" },
      { q: "Quel est le resultat de [] == false ?", a: "true", b: "false", c: "undefined", d: "Erreur", ans: "a" },
      { q: "Quelle methode crée un tableau a partir d'un iterable ?", a: "Array.from()", b: "Array.create()", c: "Array.make()", d: "new Array()", ans: "a" },
      { q: "Quel mot-cle gere les erreurs ?", a: "try/catch", b: "error/handle", c: "do/rescue",d: "handle/except", ans: "a" },
      { q: "Qu'est-ce qu'un Promesse (Promise) ?", a: "Un objet asynchrone", b: "Une fonction", c: "Un type primitif", d: "Un operateur", ans: "a" },
      { q: "Quelle methode transforme un tableau en chaine ?", a: "toString()", b: "join()", c: "string()", d: "b et c", ans: "d" },
      { q: "Quel est le 'this' dans une fonction flechee ?", a: "L'objet global", b: "L'objet parent (lexical)", c: "undefined", d: "Le contexte d'appel", ans: "b" },
      { q: "Comment importe-t-on un module ?", a: "require()", b: "import", c: "include()",d: "use()", ans: "b" },
      { q: "Quel type de donnee est 'null' ?", a: "object", b: "null", c: "undefined", d: "string", ans: "a" },
      { q: "Quelle methode filtre un tableau ?", a: "map()", b: "filter()", c: "reduce()", d: "find()", ans: "b" },
    ],
    hard: [
      { q: "Qu'est-ce que le Event Loop en JS ?", a: "Le mecanisme de traitement asynchrone", b: "Une boucle de UI", c: "Un type d'event",d: "Un observateur", ans: "a" },
      { q: "Quelle est la difference entre == et === ?", a: "Aucune", b: "=== compare aussi le type", c: "== est plus strict",d: "=== ignore le type", ans: "b" },
      { q: "Qu'est-ce qu'un generator en JS ?", a: "Une fonction qui produit des valeurs lazily", b: "Un fabricant d'objets",c: "Un type de classe",d: "Un observateur", ans: "a" },
      { q: "Quel est le prototype chain ?", a: "La chaine d'heritage d'un objet", b: "Un algorithme de tri",c: "Un type de donnees",d: "Un pattern", ans: "a" },
      { q: "Qu'est-ce que le destructuring ?", a: "Decomposer des objets/tableaux", b: "Detruire des variables",c: "Creer des copies",d: "Fusionner des objets", ans: "a" },
      { q: "Quel est le role de 'async/await' ?", a: "Gerer le code asynchrone de maniere lisible",b: "Creer des threads",c: "Paralléliser le code",d: "Gerer les erreurs", ans: "a" },
      { q: "Qu'est-ce qu'un WeakMap ?", a: "Une Map avec cles faibles (garbage collectable)",b: "Une Map lente",c: "Une Map en lecture seule",d: "Une Map partagee", ans: "a" },
      { q: "Quelle methode execute une fonction pour chaque element ?", a: "each()", b: "forEach()", c: "map()",d: "iterate()", ans: "b" },
      { q: "Quel est le resultat de '1' + 2 en JS ?", a: "3", b: '"12"', c: "Erreur", d: "NaN", ans: "b" },
      { q: "Qu'est-ce qu'un Symbol en JS ?", b: "Une chaine immmuable unique", a: "Un type primitif unique et immuable", c: "Un alias de string", d: "Un mot-cle reserve", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce qu'un Proxy en JS ?", a: "Un conteneur qui intercepte les operations sur un objet",b: "Un serveur mandataire",c: "Un type de fonction",d: "Un objet cache", ans: "a" },
      { q: "Quel est le role de 'structuredClone()' ?", a: "Cloner profondement un objet",b: "Convertir en JSON",c: "Creer un tableau",d: "Mettre a jour un objet", ans: "a" },
      { q: "Qu'est-ce que le Temporal API ?", a: "Une API pour gerer les dates/heures modernement",b: "Un timer",c: "Un type d'animation",d: "Un observateur temporel", ans: "a" },
      { q: "Quel est le role de 'Symbol.iterator' ?", a: "Rendre un objet iterant (for...of)",b: "Creer un symbole unique",c: "Definir un ordre",d: "Filtrer des donnees", ans: "a" },
      { q: "Qu'est-ce que le memory leak en JS ?", a: "Une fuite de memoire (objets non liberés)",b: "Un bug d'asynchrone",c: "Une erreur de syntaxe",d: "Un type de cache", ans: "a" },
      { q: "Quel role joue 'Object.freeze()' ?", a: "Empeche la modification d'un objet",b: "Supprime un objet",c: "Cache un objet",d: "Copie un objet", ans: "a" },
      { q: "Qu'est-ce qu'un WeakRef ?", a: "Une reference faible qui ne previent pas le GC",b: "Une reference forte",c: "Un type de pointeur",d: "Un alias d'objet", ans: "a" },
      { q: "Quel est le role de 'use strict' ?", a: "Active le mode strict (errors plus strictes)",b: "Optimise le code",c: "Desactive les warnings",d: "Active les modules", ans: "a" },
      { q: "Qu'est-ce qu'un SharedArrayBuffer ?", a: "Un buffer partage entre threads (Web Workers)",b: "Un tableau partage",c: "Un cache partage",d: "Une variable globale", ans: "a" },
      { q: "Quel est le role de 'Intl' en JS ?", a: "L'API d'internationalisation",b: "Un framework UI",c: "Un systeme d'evenements",d: "Un type de module", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce qu'un Atomics en JS ?", a: "Des operations atomiques pour le multithreading",b: "Des composants UI",c: "Un type d'objet",d: "Un pattern de design", ans: "a" },
      { q: "Quel est le role de 'ArrayBuffer' ?", a: "Alloue un buffer binaire brut",b: "Un tableau dynamique",c: "Un string binaire",d: "Un type de cache", ans: "a" },
      { q: "Qu'est-ce qu'un ShadowRealm en JS ?", a: "Un contexte d'execution isole (proposal)",b: "Un mode incognito",c: "Un type de Worker",d: "Un cache securise", ans: "a" },
      { q: "Quel est le role de 'DataView' ?", a: "Lire/ecrire dans un ArrayBuffer avec differentes representations",b: "Afficher des donnees",c: "Convertir des types",d: "Gerer le DOM", ans: "a" },
      { q: "Qu'est-ce que l'Observable proposal en JS ?", a: "Un flux de donnees reactives (proposal)",b: "Un observateur DOM",c: "Un type d'evenement",d: "Un pattern MVC", ans: "a" },
      { q: "Quel est le role de 'Promise.any()' ?", a: "Resout la premiere promesse tenue",b: "Resout toutes les promesses",c: "Rejette toutes les promesses",d: "Attend la derniere", ans: "a" },
      { q: "Qu'est-ce qu'un pipeline operator (|>) ?", a: "Enchaine les appels de fonctions (proposal)",b: "Operateur bit a bit",c: "Un operateur logique",d: "Un type d'affectation", ans: "a" },
      { q: "Quel est le role de 'WeakFinalizationRegistry' ?", a: "Nettoie des ressources quand des objets sont GC",b: "Enregistre des callbacks",c: "Cache des objets",d: "Gere les weak references", ans: "a" },
      { q: "Qu'est-ce que le Record & Tuple proposal ?", a: "Des types de donnees immuables primitifs",b: "Des tableaux speciaux",c: "Des objets speciaux",d: "Des fonctions pures", ans: "a" },
      { q: "Quel est le role de 'import.meta' ?", a: "Fournit des metadonnees sur le module courant",b: "Importe dynamiquement",c: "Modifie le module",d: "Exporte le module", ans: "a" },
    ],
  },
  TypeScript: {
    easy: [
      { q: "Quel est le fichier de config TypeScript ?", a: "tsconfig.json", b: "typescript.json", c: "config.ts",d: ".tsconfig", ans: "a" },
      { q: "Comment declare-t-on un type ?", a: "type Name = string", b: "typedef string Name",c: "alias string Name",d: "define type Name", ans: "a" },
      { q: "Quel mot-cle definit une interface ?", a: "interface", b: "type", c: "struct",d: "class", ans: "a" },
      { q: "Que fait le compilateur TS ?", a: "Compile en JavaScript", b: "Interprete le code",c: "Optimise le DOM",d: "Gere les packages", ans: "a" },
      { q: "Comment ajoute-t-on un type a un parametre ?", a: "param: type", b: "type param",c: "(type) param",d: "param as type", ans: "a" },
      { q: "Quel est le type de '42' en TS ?", a: "number", b: "int", c: "float",d: "numeric", ans: "a" },
      { q: "Quel est le type d'un tableau de strings ?", a: "string[]", b: "array<string>",c: "strings",d: "[string]", ans: "a" },
      { q: "Comment rend-on une propriete optionnelle ?", a: "?", b: "optional",c: "//",d: "!", ans: "a" },
      { q: "Quel est le type any ?", a: "N'importe quel type", b: "Type inconnu",c: "Type nul",d: "Type erreur", ans: "a" },
      { q: "Comment exporte-t-on un type ?", a: "export type", b: "type.export()",c: "module.exports type",d: "export { type }", ans: "a" },
    ],
    medium: [
      { q: "Quelle est la difference entre interface et type ?", a: "Interface est etendable, type est plus flexible",b: "Aucune difference",c: "Type est plus rapide",d: "Interface est privee", ans: "a" },
      { q: "Qu'est-ce qu'un Generique en TS ?", a: "Un type parametre (<T>)", b: "Une classe generique",c: "Un type any",d: "Un prototype", ans: "a" },
      { q: "Quel mot-cre definit une enum ?", a: "enum", b: "Enumeration",c: "const",d: "type", ans: "a" },
      { q: "Qu'est-ce qu'un type union (|) ?", a: "Un type qui accepte plusieurs types",b: "Une intersection",c: "Un tableau",d: "Un objet", ans: "a" },
      { q: "Quel est le type void ?", a: "Type de retour sans valeur",b: "Type nul",c: "Type undefined",d: "Type any", ans: "a" },
      { q: "Comment tape-t-on un evenement React ?", a: "React.ChangeEvent", b: "Event", c: "MouseEvent",d: "ChangeHandler", ans: "a" },
      { q: "Qu'est-ce qu'un type intersection (&) ?", a: "Combine deux types en un",b: "Separe les types",c: "Filtre les types",d: "Ignore les types", ans: "a" },
      { q: "Quel est le role de 'readonly' ?", a: "Empeche la modification d'une propriete",b: "Cache une propriete",c: "Rend une propriete privee",d: "Supprime une propriete", ans: "a" },
      { q: "Qu'est-ce qu'un type literal ?", a: "Un type avec une valeur exacte",b: "Un string literal",c: "Un number literal",d: "Un type any", ans: "a" },
      { q: "Comment tape-t-on une promesse ?", a: "Promise<T>", b: "Async<T>", c: "Future<T>",d: "Await<T>", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce que 'infer' en TS ?", a: "Infere un type dans un type conditionnel",b: "Devine le type",c: "Infer un type dynamique",d: "Exporte un type", ans: "a" },
      { q: "Quel est le role des 'Utility Types' (Partial, Pick, etc.) ?", a: "Transformer des types existants",b: "Creer des classes",c: "Gerer les erreurs",d: "Optimiser le code", ans: "a" },
      { q: "Qu'est-ce qu'un type conditionnel ?", a: "Un type qui depend d'une condition (T extends U ? X : Y)",b: "Un booleen",c: "Un switch de types",d: "Un type any", ans: "a" },
      { q: "Quel est le role de 'satisfies' en TS 4.9 ?", a: "Verifie qu'une expression satisfait un type sans le changer",b: "Satisfait une contrainte",c: "Valide un type",d: "Asserte un type", ans: "a" },
      { q: "Qu'est-ce qu'un type mapped ?", a: "Un type qui transforme les cles d'un objet",b: "Un type carte",c: "Un tableau mappe",d: "Un type any", ans: "a" },
      { q: "Quel est le role de 'as const' ?", a: "Rend un objet literal profondement immutable",b: "Convertit en constante",c: "Caste un type",d: "Exporte une constante", ans: "a" },
      { q: "Qu'est-ce qu'un type template literal ?", a: "Un type base sur des templates de string",b: "Un template React",c: "Un string literal",d: "Un type any", ans: "a" },
      { q: "Quel est le role de 'declare' ?", a: "Declare un type/variable sans implementer",b: "Declare une variable globale",c: "Declare une classe",d: "Declare un module", ans: "a" },
      { q: "Qu'est-ce qu'un Namespace en TS ?", a: "Un regroupement logique de types/fonctions",b: "Un module Node",c: "Un package",d: "Un scope global", ans: "a" },
      { q: "Quel est le role de 'moduleResolution' en tsconfig ?", a: "Comment TS resout les imports de modules",b: "Resout les conflits",c: "Gere les dependances",d: "Optimise les imports", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce qu'un type 'distributive' en TS ?", a: "Un type qui se distribue sur les unions",b: "Un type partage",c: "Un type any",d: "Un type global", ans: "a" },
      { q: "Quel est le role de 'Conditional Types' avec infer ?", a: "Extraire des types imbriques",b: "Tester des conditions",c: "Comparer des types",d: "Valider des types", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Recursive' en TS ?", a: "Un type qui s'appelle lui-meme",b: "Un type infini",c: "Un type any",d: "Un type circulaire", ans: "a" },
      { q: "Quel est le role de 'const' type parameter ?", a: "Preserve les literals dans les generiques",b: "Rend un parametre constant",c: "Optimise les types",d: "Cache les types", ans: "a" },
      { q: "Qu'est-ce qu'un Decorator en TS ?", a: "Un meta-programme pour modifier des classes/membres",b: "Un style CSS",c: "Un pattern UI",d: "Un observateur", ans: "a" },
      { q: "Quel est le role de 'Path Remapping' (paths) en tsconfig ?", a: "Rediriger les imports vers des chemins specifiques",b: "Modifier les chemins de fichiers",c: "Optimiser les imports",d: "Gérer les alias", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Branded' ?", a: "Un type avec un tag pour eviter les confusions",b: "Un type special",c: "Un type any",d: "Un type global", ans: "a" },
      { q: "Quel est le role de 'Exhaustive switch' avec never ?", a: "Garantir que tous les cas sont couverts",b: "Terminer le switch",c: "Optimiser le switch",d: "Catch les erreurs", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Higher-Order' en TS ?", a: "Un type qui prend ou retourne un type fonction",b: "Un type complexe",c: "Un type any",d: "Un type simple", ans: "a" },
      { q: "Quel est le role de 'Assertions' (asserts) en TS ?", a: "Affirmer qu'un type est vrai a l'execution",b: "Verifier un type",c: "Tester un type",d: "Caster un type", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce qu'un type-level computation en TS ?", a: "Calculer des types a la compilation avec des types recursifs",b: "Optimiser le code",c: "Calculer des valeurs",d: "Compiler le code", ans: "a" },
      { q: "Quel est le role de 'Type-level JSON Parser' ?", a: "Parser du JSON entierement au niveau des types",b: "Parser du JSON runtime",c: "Convertir en JSON",d: "Valider du JSON", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Type Safe Builder' ?", a: "Un pattern pour construire des objets de maniere type-safe",b: "Un constructeur",c: "Un type any",d: "Un factory pattern", ans: "a" },
      { q: "Quel est le role de 'Variadic Tuple Types' ?", a: "Gerer des tuples de longueur variable",b: "Creer des tableaux",c: "Gerer des listes",d: "Fusionner des tableaux", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Phantom' ?", a: "Un type utilise uniquement pour le typage, pas a l'execution",b: "Un type invisible",c: "Un type any",d: "Un type cache", ans: "a" },
      { q: "Quel est le role de 'Negative Array Index' types ?", a: "Taper des index negatifs dans les tableaux",b: "Supprimer des elements",c: "Inverser un tableau",d: "Acceder aux derniers elements", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Turing Complete' en TS ?", a: "Le systeme de types TS peut simuler une machine de Turing",b: "Un type special",c: "Un type any",d: "Un type global", ans: "a" },
      { q: "Quel est le role de 'Endo' types (A => A) ?", a: "Verifier qu'une transformation preserve le type",b: "Transformer des types",c: "Convertir des types",d: "Fusionner des types", ans: "a" },
      { q: "Qu'est-ce qu'un type 'Adjacency Matrix' en TS ?", a: "Representer un graphe entierement au niveau des types",b: "Une matrice numerique",c: "Un tableau 2D",d: "Un type any", ans: "a" },
      { q: "Quel est le role de 'Type-safe printf' en TS ?", a: "Verifier les arguments d'un format string a la compilation",b: "Afficher du texte",c: "Formater des strings",d: "Parser des strings", ans: "a" },
    ],
  },
  React: {
    easy: [
      { q: "Quel hook gere l'etat dans un composant ?", a: "useState", b: "useEffect", c: "useRef", d: "useMemo", ans: "a" },
      { q: "Comment cree-t-on un composant fonction ?", a: "function Composant() {}", b: "class Composant {}", c: "create Composant()", d: "new Composant()", ans: "a" },
      { q: "Quel hook effectue des effets de bord ?", a: "useState", b: "useEffect", c: "useMemo", d: "useCallback", ans: "b" },
      { q: "Comment passe-t-on des donnees a un composant ?", a: "props", b: "state", c: "args", d: "params", ans: "a" },
      { q: "Quel framework est React ?", a: "Backend", b: "Frontend (Bibliothèque UI)", c: "Base de données", d: "ORM", ans: "b" },
      { q: "Quel fichier est l'entree d'une app React ?", a: "main.tsx", b: "app.tsx", c: "index.html",d: "App.js", ans: "a" },
      { q: "Comment affiche-t-on du JSX ?", a: "return <div>", b: "print(<div>)", c: "echo <div>",d: "display <div>", ans: "a" },
      { q: "Quel est le hook pour les refs ?", a: "useRef", b: "useReference", c: "useDom",d: "useCurrent", ans: "a" },
      { q: "Comment appelle-t-on un composant enfant ?", a: "<Enfant />", b: "<Enfant />", c: "Enfant()",d: "call Enfant", ans: "b" },
      { q: "Quel est le return d'un composant React ?", a: "JSX (elements UI)", b: "HTML", c: "String",d: "DOM", ans: "a" },
    ],
    medium: [
      { q: "Quel hook gere le contexte ?", a: "useContext", b: "useState", c: "useProvider",d: "useConsumer", ans: "a" },
      { q: "Comment gere-t-on les formulaires en React ?", a: "Controlled components", b: "Uncontrolled",c: "Forms API",d: "Formik only", ans: "a" },
      { q: "Quel hook optimise les calculs couteux ?", a: "useMemo", b: "useCallback", c: "useEffect",d: "useRef", ans: "a" },
      { q: "Qu'est-ce que le lifting state up ?", a: "Monter l'etat vers le composant parent",b: "Monter un composant",c: "Gerer l'etat local",d: "Utiliser un contexte", ans: "a" },
      { q: "Quel hook memorise une fonction ?", a: "useCallback", b: "useMemo", c: "useRef",d: "useEffect", ans: "a" },
      { q: "Qu'est-ce que React.memo() ?", a: "Evite les re-rendus inutiles",b: "Memoire le composant",c: "Cache le state",d: "Optimise le DOM", ans: "a" },
      { q: "Comment gere-t-on les effets de bord avec cleanup ?", a: "Fonction de retour dans useEffect",b: "useCleanup()",c: "return dans useState",d: "useDestroy()", ans: "a" },
      { q: "Quel hook partage un state global ?", a: "useContext + useState", b: "useGlobal", c: "useStore",d: "useShared", ans: "a" },
      { q: "Qu'est-ce que le Virtual DOM ?", a: "Une representation legere du DOM reelle",b: "Le vrai DOM",c: "Un cache",d: "Un serveur virtuel", ans: "a" },
      { q: "Quelle methode ajoute un element a un tableau d'etat ?", a: "setArr([...arr, newElement])", b: "arr.add()", c: "push()",d: "append()", ans: "a" },
    ],
    hard: [
      { q: "Quel est le role de useCallback ?", a: "Memorise une fonction entre les render",b: "Cree un callback",c: "Gere les evenements",d: "Optimise le DOM", ans: "a" },
      { q: "Qu'est-ce que le Concurrent Mode en React ?", a: "Rendu asynchrone et prioritaire",b: "Multithreading",c: "Parallel rendering",d: "Worker threads", ans: "a" },
      { q: "Quel hook gere les refs de callback ?", a: "useCallback ref", b: "useRef(null)", c: "createRef",d: "useImperativeHandle", ans: "a" },
      { q: "Qu'est-ce que Suspense en React ?", a: "Affiche un fallback pendant le chargement asynchrone",b: "Suspend le composant",c: "Cache le contenu",d: "Pause les animations", ans: "a" },
      { q: "Quel est le role de useImperativeHandle ?", a: "Personnalise la valeur d'une ref",b: "Gere les imperatifs",c: "Cree des refs",d: "Modifie le DOM", ans: "a" },
      { q: "Qu'est-ce que React.memo() vs useMemo() ?", a: "memo=cache composant, useMemo=cache valeur",b: "Identiques",c: "memo=cache valeur, useMemo=cache composant",d: "Aucune difference", ans: "a" },
      { q: "Quel pattern evite la prop drilling ?", a: "Context API + useReducer", b: "Redux only",c: "Props drilling",d: "Event bubbling", ans: "a" },
      { q: "Qu'est-ce que le lazy loading en React ?", a: "Chargement differe des composants",b: "Lazy state",c: "Infinite scroll",d: "Deferred rendering", ans: "a" },
      { q: "Quel hook gere les transitions ?", a: "useTransition", b: "useDeferred", c: "useAsync",d: "useConcurrent", ans: "a" },
      { q: "Qu'est-ce que le Server Components (RSC) ?", a: "Composants rendus cote serveur",b: "Composants Node.js",c: "Backend React",d: "SSR uniquement", ans: "a" },
    ],
    expert: [
      { q: "Quel est le role de useId() ?", a: "Genere un ID unique et stable (SSR safe)",b: "Identifie un composant",c: "Gere les cles",d: "Optimise le rendu", ans: "a" },
      { q: "Qu'est-ce que le useEffect cleanup ?", a: "Fonction retournee dans useEffect pour nettoyer",b: "Un timeout",c: "Un garbage collector",d: "Un destructeur", ans: "a" },
      { q: "Quel hook differe les effets de bord ?", a: "useEffect avec dependances", b: "useDebounce",c: "useDelay",d: "useTimeout", ans: "a" },
      { q: "Qu'est-ce que le useDeferredValue() ?", a: "Retarde la mise a jour d'une valeur",b: "Cache une valeur",c: "Differencie les valeurs",d: "Optimise les calculs", ans: "a" },
      { q: "Quel pattern est le Compound Components ?", a: "Composants qui partagent un etat implicite",b: "Composes multiples",c: "Enfants composes",d: "High-order component", ans: "a" },
      { q: "Qu'est-ce que le Error Boundary ?", a: "Composant React qui attrape les erreurs",b: "Un try/catch global",c: "Un pare-feu",d: "Un middleware", ans: "a" },
      { q: "Quel hook gerer un state complexe ?", a: "useReducer", b: "useState", c: "useComplex",d: "useObject", ans: "a" },
      { q: "Qu'est-ce que le render props pattern ?", a: "Passer une fonction comme prop pour render du contenu",b: "Props de rendu",c: "Props dynamiques",d: "Props de composant", ans: "a" },
      { q: "Quel est le role de useSyncExternalStore() ?", a: "Synchroniser un store externe (Redux, Zustand)",b: "Cree un store",c: "Cache le state",d: "Gere les effets", ans: "a" },
      { q: "Qu'est-ce que React Compiler (ex React Forget) ?", a: "Compile automatiquement pour optimiser les re-rendus",b: "Compile le JSX",c: "Optimise le bundle",d: "Genere le code", ans: "a" },
    ],
    master: [
      { q: "Quel est le role de useOptimistic() ?", a: "Affiche un etat optimiste avant la resolution",b: "Optimise les performances",c: "Cache le state",d: "Genere du code", ans: "a" },
      { q: "Qu'est-ce que le use() hook en React 19 ?", a: "Lit une ressource (Promise/Context) dans le rendu",b: "Utilise un composant",c: "Charge un module",d: "Gere les effets", ans: "a" },
      { q: "Quel est le role de useActionState() ?", a: "Gere l'etat d'un formulaire avec actions",b: "Cree une action",c: "Gere les evenements",d: "Optimise les actions", ans: "a" },
      { q: "Qu'est-ce que React Server Actions ?", a: "Fonctions executees cote serveur appelees depuis le client",b: "Actions serveur",c: "API REST",d: "GraphQL", ans: "a" },
      { q: "Quel est le role de useRef() avance ?", a: "Stocke des valeurs mutables sans re-render",b: "Cree des refs DOM",c: "Gere les timers",d: "Cache des donnees", ans: "a" },
      { q: "Qu'est-ce que le Selective Hydration ?", a: "Hydrate les composants selon la priorite",b: "Hydrate tout",c: "Cache l'hydratation",d: "Differe l'hydratation", ans: "a" },
      { q: "Quel est le role de useEffectEvent() (proposal) ?", a: "Creer des fonctions stables pour les effets",b: "Gere les evenements",c: "Cree des callbacks",d: "Optimise les effets", ans: "a" },
      { q: "Qu'est-ce que le React DevTools Profiler ?", a: "Analyse les performances de rendu",b: "Debug le code",c: "Profile le reseau",d: "Mesure le bundle", ans: "a" },
      { q: "Quel pattern est le Renderless Component ?", a: "Composant qui ne rend que via ses children",b: "Composant vide",c: "Composant invisible",d: "Composant sans UI", ans: "a" },
      { q: "Quel est le role de la reconciliation dans React ?", a: "Comparer l'ancien et le nouveau Virtual DOM",b: "Reconcilier les conflits",c: "Merger le state",d: "Synchroniser les donnees", ans: "a" },
    ],
  },
  NodeJS: {
    easy: [
      { q: "Quel fichier decrit les dependances Node.js ?", a: "package.json", b: "node.config", c: "deps.json", d: "modules.json", ans: "a" },
      { q: "Comment installe-t-on un package ?", a: "npm install", b: "node install", c: "npm get", d: "node get", ans: "a" },
      { q: "Quel module affiche dans le console ?", a: "console.log()", b: "print()", c: "sys.log()", d: "out.log()", ans: "a" },
      { q: "Quel est le runtime JavaScript cote serveur ?", a: "Node.js", b: "Deno", c: "Bun", d: "Tous", ans: "d" },
      { q: "Comment importe-t-on un module CommonJS ?", a: "require()", b: "import", c: "include()", d: "use()", ans: "a" },
      { q: "Quel fichier est l'entree d'un projet Node ?", a: "index.js / server.js", b: "main.js", c: "app.js", d: "start.js", ans: "a" },
      { q: "Comment lance-t-on un script Node ?", a: "node script.js", b: "run script.js", c: "start script.js", d: "exec script.js", ans: "a" },
      { q: "Quel module lit des fichiers ?", a: "fs", b: "file", c: "read", d: "io", ans: "a" },
      { q: "Quel module gere les chemins ?", a: "path", b: "fs", c: "dir", d: "file", ans: "a" },
      { q: "Comment cree-t-on un serveur HTTP basique ?", a: "http.createServer()", b: "server.create()", c: "express()", d: "new Server()", ans: "a" },
    ],
    medium: [
      { q: "Quel framework web populaire pour Node ?", a: "Express", b: "Laravel", c: "Django", d: "Rails", ans: "a" },
      { q: "Qu'est-ce qu'un middleware Express ?", a: "Fonction qui intercepte les requetes", b: "Un composant UI", c: "Un module", d: "Un plugin", ans: "a" },
      { q: "Comment parse le JSON d'une requete ?", a: "express.json()", b: "JSON.parse()", c: "body-parser", d: "a et c", ans: "d" },
      { q: "Quel module gere les variables d'environnement ?", a: "process.env", b: "env.config", c: "dotenv", d: "a et c", ans: "d" },
      { q: "Qu'est-ce que npm ?", a: "Gestionnaire de packages Node.js", b: "Un framework", c: "Un runtime",d: "Un serveur", ans: "a" },
      { q: "Quelle methode recoit les requetes GET ?", a: "app.get()", b: "app.request()", c: "app.listen()",d: "app.route()", ans: "a" },
      { q: "Qu'est-ce qu'un callback en Node.js ?", a: "Fonction appelee apres une operation asynchrone",b: "Un evenement",c: "Un timer",d: "Un module", ans: "a" },
      { q: "Quel module cree un serveur Express ?", a: "express()", b: "http.createServer()",c: "server.create()",d: "app.run()", ans: "a" },
      { q: "Comment envoie-t-on une reponse JSON ?", a: "res.json()", b: "res.send()", c: "res.end()",d: "a et b", ans: "d" },
      { q: "Quel est le port par defaut de Node.js ?", a: "3000", b: "8080", c: "Aucun", d: "80", ans: "c" },
    ],
    hard: [
      { q: "Qu'est-ce que le Event Loop en Node.js ?", a: "Le mecanisme de traitement asynchrone",b: "Un evenement UI",c: "Un type de timer",d: "Un observateur", ans: "a" },
      { q: "Quelle est la difference entre process.nextTick et setImmediate ?", a: "nextTick avant le loop, immediate apres",b: "Aucune",c: "nextTick est plus lent",d: "immediate est asynchrone", ans: "a" },
      { q: "Qu'est-ce qu'un Stream en Node.js ?", a: "Flux de donnees pour les gros volumes",b: "Un video stream",c: "Un audio stream",d: "Un websocket", ans: "a" },
      { q: "Quel module gere les processus enfant ?", a: "child_process", b: "cluster", c: "worker_threads",d: "toutes", ans: "d" },
      { q: "Qu'est-ce que le clustering en Node.js ?", a: "Partager la charge entre processus",b: "Grouper des donnees",c: "Organiser le code",d: "Gerer les packages", ans: "a" },
      { q: "Quel est le role de 'Buffer' en Node ?", a: "Manipuler des donnees binaires",b: "Mettre en tampon",c: "Cacher des donnees",d: "Optimiser le code", ans: "a" },
      { q: "Qu'est-ce qu'un Worker Thread ?", a: "Thread supplementaire pour le parallellisme",b: "Un employe",c: "Un thread principal",d: "Un thread UI", ans: "a" },
      { q: "Quel module gere les sockets TCP ?", a: "net", b: "socket", c: "tcp", d: "http", ans: "a" },
      { q: "Qu'est-ce que le Backpressure en Streams ?", a: "Quand le lecteur est plus lent que l'ecrivain",b: "Une erreur",c: "Un timeout",d: "Un bug", ans: "a" },
      { q: "Quel est le role de 'require.resolve()' ?", a: "Resoudre le chemin d'un module sans l'importer",b: "Recharger un module",c: "Supprimer un module",d: "Installer un module", ans: "a" },
    ],
    expert: [
      { q: "Quel est le role de 'vm' module en Node.js ?", a: "Creer un contexte d'execution JS isole",b: "Machine virtuelle",c: "Gerer la memoire",d: "Optimiser le code", ans: "a" },
      { q: "Qu'est-ce que le 'Module._compile' en Node ?", a: "Compile un module avant son execution",b: "Optimise le module",c: "Cache le module",d: "Charge le module", ans: "a" },
      { q: "Quel est le role de 'async_hooks' ?", a: "Tracer le cycle de vie des operations asynchrones",b: "Creer des hooks asynchrones",c: "Gerer les evenements",d: "Optimiser les callbacks", ans: "a" },
      { q: "Qu'est-ce que le 'v8.serialize()' en Node ?", a: "Serialiser des objets JS en binaire (V8)",b: "JSON serializer",c: "Protobuf",d: "MessagePack", ans: "a" },
      { q: "Quel est le role de 'perf_hooks' ?", a: "Mesurer les performances du code",b: "Gerer les hooks",c: "Optimiser le code",d: "Profiler le reseau", ans: "a" },
      { q: "Qu'est-ce que le 'report' module en Node ?", a: "Generer des rapports d'erreur/diagnostic",b: "Rapports financiers",c: "Rapports de code",d: "Rapports de build", ans: "a" },
      { q: "Quel est le role de 'diagnostics_channel' ?", a: "Publier/s'abonner a des evenements de diagnostic",b: "Canal de communication",c: "Channel de debugging",d: "Observer les erreurs", ans: "a" },
      { q: "Qu'est-ce qu'un 'Diagnostic Report' en Node.js ?", a: "Rapport JSON d'information systeme/erreur",b: "Un bug report",c: "Un log",d: "Un metric", ans: "a" },
      { q: "Quel est le role de 'isolate' dans V8/Node ?", a: "Instance V8 isolee pour la securite",b: "Isoler les erreurs",c: "Isoler les modules",d: "Isoler les threads", ans: "a" },
      { q: "Qu'est-ce que le 'Hooks' system dans Node.js ?", a: "Intercepter les chargements de modules",b: "Evenements globaux",c: "Middleware",d: "Plugins", ans: "a" },
    ],
    master: [
      { q: "Quel est le role de 'node:sea' (Single Executable Apps) ?", a: "Packager une app Node en un seul executabe",b: "Creer un package",c: "Installer Node",d: "Gere les packages", ans: "a" },
      { q: "Qu'est-ce que le 'Permission Model' en Node.js ?", a: "Systeme de permissions granulaires (fichiers, reseau)",b: "Droits d'admin",c: "Gestion des users",d: "Roles", ans: "a" },
      { q: "Quel est le role de 'test_runner' (node:test) ?", a: "Runner de tests natif sans framework externe",b: "Un testeur HTTP",c: "Un testeur de performance",d: "Un load tester", ans: "a" },
      { q: "Qu'est-ce que le 'fetch' natif en Node 18+ ?", a: "API Fetch implementee nativement (sans node-fetch)",b: "Un package externe",c: "Un client HTTP",d: "Un wrapper", ans: "a" },
      { q: "Quel est le role de '--experimental-strip-types' ?", a: "Support natif des .ts sans compilation",b: "Supprimer les types",c: "Debugger TypeScript",d: "Optimiser le build", ans: "a" },
      { q: "Qu'est-ce que 'Mock Agent' en Node.js ?", a: "Intercepter/mock les requetes reseau (undici)",b: "Un agent IA",c: "Un bot",d: "Un proxy", ans: "a" },
      { q: "Quel est le role de 'navigator' global en Node 21+ ?", a: "API Navigator compatible navigateur",b: "Navigation web",c: "Geolocation",d: "Historique", ans: "a" },
      { q: "Qu'est-ce que le 'WebSocket' natif en Node.js ?", a: "Client WebSocket natif (pas de package externe)",b: "Un serveur WebSocket",c: "Un protocol",d: "Un framework", ans: "a" },
      { q: "Quel est le role de 'AbortSignal.timeout()' ?", a: "Timeout pour les operations asynchrones avec abort",b: "Timer global",c: "Arreter le server",d: "Timeout HTTP", ans: "a" },
      { q: "Qu'est-ce que le 'structuredClone' en Node.js ?", a: "Clonage profond natif d'objets JS",b: "Clone un fichier",c: "Clone un processus",d: "Clone un module", ans: "a" },
    ],
  },
  Python: {
    easy: [
      { q: "Comment affiche-t-on du texte en Python ?", a: "print()", b: "echo()", c: "console.log()",d: "display()", ans: "a" },
      { q: "Comment declare-t-on une variable ?", a: "var x = 5", b: "x = 5", c: "let x = 5",d: "dim x = 5", ans: "b" },
      { q: "Quel fichier est l'extension d'un script Python ?", a: ".py", b: ".python", c: ".pt", d: ".script", ans: "a" },
      { q: "Comment lance-t-on un script Python ?", a: "python script.py", b: "run script.py", c: "start script.py",d: "exec script.py", ans: "a" },
      { q: "Quel est le type d'une liste en Python ?", a: "list", b: "array", c: "Array", d: "List", ans: "a" },
      { q: "Comment cree-t-on une liste ?", a: "[] ou list()", b: "array()", c: "{}",d: "new List()", ans: "a" },
      { q: "Quel mot-cle definit une fonction ?", a: "def", b: "function", c: "func", d: "fn", ans: "a" },
      { q: "Quel est le commentaire sur une ligne ?", a: "#", b: "//", c: "--", d: "/*", ans: "a" },
      { q: "Quel operateur puissance ?", a: "**", b: "^", c: "pow", d: "^^", ans: "a" },
      { q: "Quel est le type d'un dictionnaire ?", a: "dict", b: "hash", c: "map",d: "object", ans: "a" },
    ],
    medium: [
      { q: "Qu'est-ce qu'un decorateur en Python ?", a: "Fonction qui modifie une autre fonction/classe",b: "Un style CSS",c: "Un pattern UI",d: "Un module", ans: "a" },
      { q: "Quelle est la syntaxe d'un decorateur ?", a: "@decorateur", b: "#decorateur", c: "$decorateur",d: "*decorateur", ans: "a" },
      { q: "Qu'est-ce que *args et **kwargs ?", a: "Arguments positionnels et nommes variable",b: "Variables globales",c: "Pointeurs",d: "Constantes", ans: "a" },
      { q: "Quel mot-cle cree une classe ?", a: "class", b: "object", c: "def",d: "type", ans: "a" },
      { q: "Qu'est-ce que le 'self' en Python ?", a: "Reference a l'instance courante",b: "Le module lui-meme",c: "La classe parente",d: "Le contexte", ans: "a" },
      { q: "Quelle methode est appelee a l'initialisation ?", a: "__init__", b: "constructor", c: "init()",d: "new()", ans: "a" },
      { q: "Comment importe-t-on un module ?", a: "import module", b: "require(module)", c: "include(module)",d: "use(module)", ans: "a" },
      { q: "Qu'est-ce qu'un generator (yield) ?", a: "Fonction qui produit des valeurs laziment",b: "Un createur d'objets",c: "Un type de boucle",d: "Un observateur", ans: "a" },
      { q: "Quelle librairie gere les maths en Python ?", a: "math", b: "numpy", c: "cmath", d: "maths", ans: "a" },
      { q: "Quel type de retour indique rien ?", a: "None", b: "void", c: "null",d: "undefined", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce que le GIL en Python ?", a: "Global Interpreter Lock (limite le multithreading)",b: "Un module",c: "Un type",d: "Un pattern", ans: "a" },
      { q: "Quel est le difference entre列表推导式 et generator expression ?", a: "List = tout en memoire, Gen = lazily",b: "Aucune",c: "Gen est plus rapide",d: "List est async", ans: "a" },
      { q: "Qu'est-ce qu'un context manager (with) ?", a: "Gere le lifecycle des ressources (ouverture/fermeture)",b: "Un gestionnaire de contexte React",c: "Un middleware",d: "Un plugin", ans: "a" },
      { q: "Quel est le role de __slots__ ?", a: "Optimise la memoire en limitant les attributs",b: "Cree des slots UI",c: "Gere les permissions",d: "Cache des donnees", ans: "a" },
      { q: "Qu'est-ce que le metaclass en Python ?", a: "Classe qui definit comment les classes sont creees",b: "Classe abstraite",c: "Classe parente",d: "Classe interface", ans: "a" },
      { q: "Quel est le role de __all__ ?", a: "Definit ce qui est exporte par un module",b: "Exporte tout",c: "Importe tout",d: "Cache tout", ans: "a" },
      { q: "Qu'est-ce qu'un dataclass en Python ?", a: "Classe avec __init__ genere automatiquement",b: "Classe de donnees",c: "Classe abstraite",d: "Classe singleton", ans: "a" },
      { q: "Quel est le role de typing en Python ?", a: "Ajouter des type hints statiques",b: "Gerer le clavier",c: "Definir les types",d: "Caster les types", ans: "a" },
      { q: "Qu'est-ce que le asyncio en Python ?", a: "Programmation asynchrone avec event loop",b: "Un type de boucle",c: "Un module math",d: "Un framework web", ans: "a" },
      { q: "Quel role joue __repr__ vs __str__ ?", a: "repr=pour debuggers, str=pour humains",b: "Identiques",c: "repr=pour UI, str=pour logs",d: "Aucune difference", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce qu'un descriptor en Python ?", a: "Objet avec __get__/__set__/__delete__ pour controler l'acces",b: "Un decorateur",c: "Un type",d: "Un module", ans: "a" },
      { q: "Quel est le role de __init_subclass__ ?", a: "Personnaliser la creation de sous-classes",b: "Initialiser les classes",c: "Creer des instances",d: "Modifier les metaclasses", ans: "a" },
      { q: "Qu'est-ce que le Protocol (structural subtyping) ?", a: "Typage structurel sans inheritance",b: "Un protocole reseau",c: "Un design pattern",d: "Un module", ans: "a" },
      { q: "Quel est le role de __set_name__ ?", a: "Notifier un descriptor du nom de l'attribut qu'il decrit",b: "Nommer un attribut",c: "Renommer une classe",d: "Definir un nom", ans: "a" },
      { q: "Qu'est-ce qu'un freeze en Python (dataclasses) ?", a: "Empeche la modification des attributs d'une instance",b: "Gel le programme",c: "Arrete le thread",d: "Cache l'instance", ans: "a" },
      { q: "Quel est le role de __class_getitem__ ?", a: "Supporte la notation generique (Class[T])",b: "Accede a la classe",c: "Modifie la classe",d: "Cree une sous-classe", ans: "a" },
      { q: "Qu'est-ce qu'un cached_property ?", a: "Propriete dont la valeur est calculee une seule fois",b: "Une propriete cachee",c: "Un decorateur async",d: "Un type de memoire", ans: "a" },
      { q: "Quel est le role de __finalize__ ?", a: "Nettoie les objets avant leur destruction (gc)",b: "Finalise le build",c: "Termine un processus",d: "Valide les donnees", ans: "a" },
      { q: "Qu'est-ce que le ' walrus operator' (:=) ?", a: "Affecte et retourne une valeur dans une expression",b: "Un operateur logique",c: "Un decorateur",d: "Un type", ans: "a" },
      { q: "Quel est le role de __init_subclass__ ?", a: "Hook appele quand une sous-classe est creee",b: "Initialise les instances",c: "Cree des metaclasses",d: "Importe les modules", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce qu'un PEP (Python Enhancement Proposal) ?", a: "Proposition d'amelioration de Python",b: "Un package",c: "Un module",d: "Un protocole", ans: "a" },
      { q: "Quel est le role de __abstractmethods__ ?", a: "Liste les methodes abstraites d'une classe",b: "Cree des methodes",c: "Cache les methodes",d: "Supprime les methodes", ans: "a" },
      { q: "Qu'est-ce que le 'shallow copy' vs 'deep copy' ?", a: "Shallow = copie de reference, Deep = copie recursive",b: "Identiques",c: "Shallow est plus lent",d: "Deep est plus lent", ans: "a" },
      { q: "Quel est le role de __reduce__ / __reduce_ex__ ?", a: "Serialiser un objet pour pickle/copy",b: "Reduire le code",c: "Optimiser les performances",d: "Compresser les donnees", ans: "a" },
      { q: "Qu'est-ce que le contextvars en Python ?", a: "Variables specifiques a un contexte async",b: "Variables globales",c: "Variables d'environnement",d: "Variables locales", ans: "a" },
      { q: "Quel est le role de __init__ co-routine ?", a: "Async init pour les objets asynchrones",b: "Init synchronise",c: "Init parallele",d: "Init differee", ans: "a" },
      { q: "Qu'est-ce que le 'immutability' avec frozen dataclasses ?", a: "Instances dont les attributs ne changent pas",b: "Classe immutable",c: "Type immutable",d: "Variable constante", ans: "a" },
      { q: "Quel est le role de __init_subclass__ avec keyword args ?", a: "Personnaliser la creation de sous-classes avec options",b: "Ajouter des options",c: "Modifier les keywords",d: "Cree des options", ans: "a" },
      { q: "Qu'est-ce que le 'TypeVarTuple' (PEP 646) ?", a: "Tuple de types parametrique",b: "Un tuple de variables",c: "Un type variadique",d: "Un tuple dynamique", ans: "a" },
      { q: "Quel est le role de 'Unpack' (PEP 646) ?", a: "Deballer un tuple de types dans un type generique",b: "Deballer un tuple",c: "Importer des types",d: "Exporter des types", ans: "a" },
    ],
  },
  SQL: {
    easy: [
      { q: "Quelle requete recupere des donnees ?", a: "SELECT", b: "GET", c: "FETCH", d: "RETRIEVE", ans: "a" },
      { q: "Quelle clause filtre les resultats ?", a: "WHERE", b: "FILTER", c: "HAVING",d: "FIND", ans: "a" },
      { q: "Comment trie-t-on les resultats ?", a: "ORDER BY", b: "SORT BY", c: "ARRANGE BY",d: "GROUP BY", ans: "a" },
      { q: "Quelle requete ajoute une ligne ?", a: "INSERT INTO", b: "ADD", c: "CREATE",d: "PUT", ans: "a" },
      { q: "Quelle requete supprime des donnees ?", a: "DELETE", b: "REMOVE", c: "DROP",d: "DESTROY", ans: "a" },
      { q: "Quelle requete modifie des donnees ?", a: "UPDATE", b: "MODIFY", c: "CHANGE",d: "SET", ans: "a" },
      { q: "Quel mot-cle supprime une table ?", a: "DROP TABLE", b: "DELETE TABLE", c: "REMOVE TABLE",d: "DESTROY TABLE", ans: "a" },
      { q: "Quelle fonction compte les lignes ?", a: "COUNT()", b: "TOTAL()", c: "SUM()",d: "NUMBER()", ans: "a" },
      { q: "Quel type de donnee stocke du texte ?", a: "VARCHAR", b: "STRING", c: "TEXT",d: "CHAR", ans: "a" },
      { q: "Comment joint-on deux tables ?", a: "JOIN", b: "MERGE", c: "COMBINE",d: "LINK", ans: "a" },
    ],
    medium: [
      { q: "Quelle est la difference entre WHERE et HAVING ?", a: "WHERE filtre les lignes, HAVING filtre les groupes",b: "Identiques",c: "HAVING est plus rapide",d: "WHERE est obsolete", ans: "a" },
      { q: "Quel type de JOIN recupere toutes les lignes d'une table ?", a: "LEFT JOIN", b: "INNER JOIN", c: "RIGHT JOIN",d: "CROSS JOIN", ans: "a" },
      { q: "Qu'est-ce qu'une sous-requete ?", a: "Requete imbriquee dans une autre",b: "Une vue",c: "Un index",d: "Un trigger", ans: "a" },
      { q: "Quel mot-cle cree un index ?", a: "CREATE INDEX", b: "ADD INDEX", c: "MAKE INDEX",d: "NEW INDEX", ans: "a" },
      { q: "Quel est le role du GROUP BY ?", a: "Grouper les lignes par valeur commune",b: "Trier les donnees",c: "Filtrer les lignes",d: "Joindre les tables", ans: "a" },
      { q: "Qu'est-ce qu'une transaction ?", a: "Ensemble d'operations atomiques",b: "Un type de donnees",c: "Un index",d: "Un trigger", ans: "a" },
      { q: "Quel mot-cle definit une cle primaire ?", a: "PRIMARY KEY", b: "UNIQUE", c: "KEY",d: "ID", ans: "a" },
      { q: "Quel est le role de LIMIT ?", a: "Limiter le nombre de resultats",b: "Limiter la taille",c: "Limiter le temps",d: "Limiter les colonnes", ans: "a" },
      { q: "Qu'est-ce qu'une vue (VIEW) ?", a: "Requete sauvegardee comme table virtuelle",b: "Une table physique",c: "Un index",d: "Un trigger", ans: "a" },
      { q: "Quel est le role du COMMIT ?", a: "Valider une transaction",b: "Annuler",c: "Sauvegarder un fichier",d: "Envoyer", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce qu'une jointure LEFT vs INNER ?", a: "LEFT garde toutes les lignes gauches, INNER seulement les correspondances",b: "Identiques",c: "LEFT est plus rapide",d: "INNER est plus flexible", ans: "a" },
      { q: "Qu'est-ce qu'un index B-Tree ?", a: "Structure d'indexation equilibree pour les recherches",b: "Un arbre generique",c: "Un type de table",d: "Un trigger", ans: "a" },
      { q: "Quelle est la normalisation 3NF ?", a: "Eliminer les dependances transitives",b: "Ajouter des indexes",c: "Denormaliser les donnees",d: "Creer des vues", ans: "a" },
      { q: "Qu'est-ce qu'un deadlock en SQL ?", a: "Blocage mutuel entre deux transactions",b: "Un bug",c: "Une erreur de syntaxe",d: "Un timeout", ans: "a" },
      { q: "Quel est le role de EXPLAIN en SQL ?", a: "Analyser le plan d'execution d'une requete",b: "Expliquer le schema",c: "Documenter le code",d: "Voir les erreurs", ans: "a" },
      { q: "Qu'est-ce qu'un stored procedure ?", a: "Requete SQL stockee et executee sur le serveur",b: "Un script",c: "Un trigger",d: "Une vue", ans: "a" },
      { q: "Quelle est la difference entre DELETE et TRUNCATE ?", a: "TRUNCATE vide la table entiere (pas de WHERE), DELETE est plus flexible",b: "Identiques",c: "TRUNCATE est plus lent",d: "DELETE est plus rapide", ans: "a" },
      { q: "Qu'est-ce qu'un ACID en BDD ?", a: "Atomicite, Consistance, Isolation, Durabilite",b: "Un type de donnees",c: "Un index",d: "Un trigger", ans: "a" },
      { q: "Quel est le role du HAVING dans une aggregation ?", a: "Filtrer les groupes apres GROUP BY",b: "Filtrer les lignes",c: "Trier les groupes",d: "Joindre les tables", ans: "a" },
      { q: "Qu'est-ce qu'uncovering index ?", a: "Index qui couvre toutes les colonnes requisees",b: "Index cache",c: "Index invisible",d: "Index partiel", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce qu'un CTE (Common Table Expression) ?", a: "Sous-requete nommée utilisable dans une requete",b: "Un type de table",c: "Un index",d: "Un trigger", ans: "a" },
      { q: "Quelle est la difference entre UNION et UNION ALL ?", a: "UNION supprime les doublons, UNION ALL garde tout",b: "Identiques",c: "UNION est plus rapide",d: "UNION ALL supprime les doublons", ans: "a" },
      { q: "Qu'est-ce qu'un partitionnement de table ?", a: "Diviser une grande table en sous-tables physiques",b: "Decouper le code",c: "Partager les donnees",d: "Indexer la table", ans: "a" },
      { q: "Quel est le role du window function (OVER) ?", a: "Effectuer des calculs sur un ensemble de lignes lies",b: "Fenetrer les donnees",c: "Trier les donnees",d: "Filtrer les donnees", ans: "a" },
      { q: "Qu'est-ce qu'un deadlock detection ?", a: "Detection automatique des blocages entre transactions",b: "Detection d'erreurs",c: "Detection de fraudes",d: "Detection de doublons", ans: "a" },
      { q: "Quel est le role de ISOLATION LEVEL ?", a: "Definir le degre d'isolation entre transactions concurrentes",b: "Niveau de securite",c: "Niveau de permissions",d: "Niveau de log", ans: "a" },
      { q: "Qu'est-ce qu'un covering index (index scan) ?", a: "Index qui evite l'acces a la table principale",b: "Index secondaire",c: "Index partiel",d: "Index unique", ans: "a" },
      { q: "Quel est le role de MERGE en SQL ?", a: "Inserer ou mettre a jour dans une seule operation",b: "Fusionner des tables",c: "Joindre des vues",d: "Unionner des requetes", ans: "a" },
      { q: "Qu'est-ce qu'un materialized view ?", a: "Vue dont les resultats sont calcules et stockes physiquement",b: "Vue physique",c: "Vue virtuelle",d: "Vue indexee", ans: "a" },
      { q: "Quel est le role de LATERAL JOIN ?", a: "Joindre avec une sous-requete qui reference les colonnes precedentes",b: "Joindre lateralement",c: "Filtrer les donnees",d: "Trier les donnees", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce qu'un Query Optimizer ?", a: "Composant qui determine le meilleur plan d'execution",b: "Un index",c: "Un trigger",d: "Une vue", ans: "a" },
      { q: "Quel est le role du 'Index Condition Pushdown' ?", a: "Pousser les conditions de filtre dans l'index",b: "Pusher les donnees",c: "Optimiser les index",d: "Filtrer les index", ans: "a" },
      { q: "Qu'est-ce qu'un 'Adaptive Hash Index' (InnoDB) ?", a: "Index hash auto-cree pour les recherches frequentes",b: "Un hash dynamique",c: "Un index statique",d: "Un trigger", ans: "a" },
      { q: "Quel est le role de 'Multi-Version Concurrency Control' (MVCC) ?", a: "Gerer les concurrences avec des versions de donnees",b: "Versions de code",c: "Versions de schema",d: "Versions de backup", ans: "a" },
      { q: "Qu'est-ce qu'un 'Buffer Pool' en InnoDB ?", a: "Cache en memoire des pages de donnees et index",b: "Un pool de connexions",c: "Un buffer de reseau",d: "Un cache disque", ans: "a" },
      { q: "Quel est le role du 'Change Buffer' en InnoDB ?", a: "Bufferiser les modifications d'index non uniques",b: "Bufferiser les changements",c: "Bufferiser les lectures",d: "Bufferiser les ecritures", ans: "a" },
      { q: "Qu'est-ce qu'un 'Predicate Pushdown' ?", a: "Pousser les conditions de filtre vers la source de donnees",b: "Pousser les predicats",c: "Filtrer les resultats",d: "Optimiser les jointures", ans: "a" },
      { q: "Quel est le role de 'Table Pruning' en InnoDB ?", a: "Reclamer l'espace des pages partiellement utilisees",b: "Supprimer les donnees",c: "Optimiser les index",d: "Compacter la table", ans: "a" },
      { q: "Qu'est-ce qu'un 'Parallel Query Execution' ?", a: "Executer les etapes d'une requete en parallele",b: "Requetes paralleles",c: "Requetes asynchrones",d: "Requetes distribuees", ans: "a" },
      { q: "Quel est le role de 'Cardinality Estimation' ?", a: "Estimer le nombre de lignes resultantes pour l'optimiseur",b: "Compter les lignes",c: "Estimer la taille",d: "Mesurer les performances", ans: "a" },
    ],
  },
  Git: {
    easy: [
      { q: "Comment initialise-t-on un depot Git ?", a: "git init", b: "git new", c: "git start",d: "git create", ans: "a" },
      { q: "Comment ajoute-t-on des fichiers ?", a: "git add", b: "git stage", c: "git put",d: "git push", ans: "a" },
      { q: "Comment commit les changements ?", a: "git commit", b: "git save", c: "git push",d: "git store", ans: "a" },
      { q: "Quel fichier ne doit jamais etre commit ?", a: "node_modules/", b: "src/", c: "README.md",d: "package.json", ans: "a" },
      { q: "Comment clone-t-on un depot ?", a: "git clone", b: "git copy", c: "git download",d: "git fork", ans: "a" },
      { q: "Quel est le fichier .gitignore ?", a: "Fichier qui ignore certains fichiers dans Git",b: "Un fichier de config",c: "Un readme",d: "Un script", ans: "a" },
      { q: "Comment affiche-t-on l'historique ?", a: "git log", b: "git history", c: "git show",d: "git list", ans: "a" },
      { q: "Comment cree-t-on une branche ?", a: "git branch", b: "git new-branch", c: "git create-branch",d: "git split", ans: "a" },
      { q: "Comment bascule-t-on de branche ?", a: "git checkout / git switch", b: "git move", c: "git change",d: "git go", ans: "a" },
      { q: "Quel statut indique un fichier modifie ?", a: "Modified", b: "Changed", c: "Updated",d: "Edited", ans: "a" },
    ],
    medium: [
      { q: "Quelle est la difference entre git pull et git fetch ?", a: "pull=fetch+merge, fetch=telecharge sans merger",b: "Identiques",c: "pull est plus lent",d: "fetch supprime", ans: "a" },
      { q: "Qu'est-ce qu'un merge conflict ?", a: "Conflit quand Git ne peut pas fusionner automatiquement",b: "Un bug",c: "Une erreur de permission",d: "Un timeout", ans: "a" },
      { q: "Quel command cree un tag ?", a: "git tag", b: "git mark", c: "git label",d: "git bookmark", ans: "a" },
      { q: "Comment stash les changements ?", a: "git stash", b: "git save", c: "git hide",d: "git cache", ans: "a" },
      { q: "Qu'est-ce que git rebase ?", a: "Reappliquer les commits sur une autre base",b: "Annuler des commits",c: "Fusionner des branches",d: "Supprimer des commits", ans: "a" },
      { q: "Comment affiche-t-on les branches ?", a: "git branch", b: "git branches", c: "git list",d: "git show", ans: "a" },
      { q: "Quelle est la difference entre merge et rebase ?", a: "merge garde l'historique, rebase le linéarise",b: "Identiques",c: "rebase est plus sur",d: "merge est plus rapide", ans: "a" },
      { q: "Comment cherry-pick un commit ?", a: "git cherry-pick <hash>", b: "git pick <hash>", c: "git copy <hash>",d: "git apply <hash>", ans: "a" },
      { q: "Qu'est-ce qu'un remote ?", a: "Depot distant (GitHub, GitLab)",b: "Un depôt local",c: "Un fichier",d: "Un script", ans: "a" },
      { q: "Comment pousse-t-on les changements ?", a: "git push", b: "git upload", c: "git send",d: "git publish", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce que git bisect ?", a: "Binaire search pour trouver le commit qui a casse quelque chose",b: "Couper une branche",c: "Fusionner deux commits",d: "Diviser le repo", ans: "a" },
      { q: "Quel est le role de git reflog ?", a: "Historique de tous les mouvements de HEAD",b: "Journal des fichiers",c: "Log des branches",d: "Historique des tags", ans: "a" },
      { q: "Qu'est-ce qu'un rebase interactif ?", a: "Modifier, reorganiser, squash des commits pendant un rebase",b: "Un rebase automatique",c: "Un merge interactif",d: "Un commit interactif", ans: "a" },
      { q: "Quel est le role de git worktree ?", a: "Gerer plusieurs working directories pour un meme repo",b: "Arborescence de travail",c: "Structure des fichiers",d: "Organisation du code", ans: "a" },
      { q: "Qu'est-ce que git blame ?", a: "Voir qui a modifie chaque ligne d'un fichier",b: "Blamer les erreurs",c: "Voir l'historique",d: "Comparer les fichiers", ans: "a" },
      { q: "Quelle est la difference entre git reset --soft, --mixed, --hard ?", a: "soft=maintient staging, mixed=annule staging, hard=supprime tout",b: "Identiques",c: "hard est le plus sur",d: "soft est irreversible", ans: "a" },
      { q: "Qu'est-ce que git submodule ?", a: "Integrer un autre depot dans celui-ci",b: "Un module du code",c: "Un package",d: "Un composant", ans: "a" },
      { q: "Quel est le role de git sparse-checkout ?", a: "Ne checkout qu'une partie du depot",b: "Sparse les commits",c: "Sparse les branches",d: "Sparse les fichiers", ans: "a" },
      { q: "Qu'est-ce qu'un hook Git ?", a: "Script execute automatiquement a certaines etapes Git",b: "Un evenement",c: "Un middleware",d: "Un plugin", ans: "a" },
      { q: "Quel est le role de git archive ?", a: "Creer une archive d'un commit sans l'historique",b: "Archiver le depot",c: "Compresser les fichiers",d: "Zipper le repo", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce que le object model de Git ?", a: "Les blobs, trees, commits et tags comme objets",b: "Un model de donnees",c: "Un schema de BDD",d: "Un pattern de design", ans: "a" },
      { q: "Quel est le role de git replace ?", a: "Remplacer un objet par un autre dans l'historique",b: "Remplacer un fichier",c: "Remplacer un commit",d: "Remplacer une branche", ans: "a" },
      { q: "Qu'est-ce que le 'plumbing' en Git ?", a: "Les commandes bas niveau (objets, refs)",b: "Les commandes UI",c: "Les commandes de nettoyage",d: "Les commandes de build", ans: "a" },
      { q: "Quel est le role de git notes ?", a: "Attacher des notes aux commits sans les modifier",b: "Prendre des notes",c: "Documenter le code",d: "Commenter les commits", ans: "a" },
      { q: "Qu'est-ce qu'un 'dangling object' en Git ?", a: "Objet non reference par aucune ref",b: "Un objet casse",c: "Un objet cache",d: "Un objet perdu", ans: "a" },
      { q: "Quel est le role de git fsck ?", a: "Verifier l'integrite des objets Git",b: "Verifier les fichiers",c: "Nettoyer le repo",d: "Reparer les branches", ans: "a" },
      { q: "Qu'est-ce que le 'packfile' en Git ?", a: "Compression des objets Git en fichiers pack",b: "Un package npm",c: "Un bundle",d: "Une archive", ans: "a" },
      { q: "Quel est le role de git maintenance ?", a: "Optimisation periodique du depot (gc, repack, etc.)",b: "Maintenance du code",c: "Nettoyage des branches",d: "Optimisation des index", ans: "a" },
      { q: "Qu'est-ce que le 'bitmapped packfile' ?", a: "Packfile avec index bitfield pour les operations rapides",b: "Un packfile compresse",c: "Un packfile indexe",d: "Un packfile special", ans: "a" },
      { q: "Quel est le role de 'multi-pack-index' (MIDX) ?", a: "Index qui couvre plusieurs packfiles",b: "Index multiple",c: "Index global",d: "Index optimise", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce que le 'commit graph' file en Git ?", a: "Cache acyclique des commits pour accelerer les traverses",b: "Un graphique des commits",c: "Un arbre de decision",d: "Un schema visuel", ans: "a" },
      { q: "Quel est le role de 'git hook run' ?", a: "Executer un hook personalise",b: "Lancer un script",c: "Gerer les hooks",d: "Installer un hook", ans: "a" },
      { q: "Qu'est-ce que 'scalar' dans Git ?", a: "Extension pour les grands depots (Microsoft)",b: "Un type de donnees",c: "Un outil de build",d: "Un framework", ans: "a" },
      { q: "Quel est le role de 'git sparse-repo' ?", a: "Ne telecharger que les fichiers necessaires (partial clone)",b: "Un depot sparse",c: "Un depot partiel",d: "Un depot leger", ans: "a" },
      { q: "Qu'est-ce que le 'reachability bitmap' ?", a: "Index bitmap pour calculer rapidemment les ensembles de commits",b: "Un index de reachabilite",c: "Un bit de reachabilite",d: "Un cache", ans: "a" },
      { q: "Quel est le role de 'git maintenance start' ?", a: "Demarrer les taches de maintenance periodiques",b: "Demarrer le depot",c: "Nettoyer le depot",d: "Optimiser le depot", ans: "a" },
      { q: "Qu'est-ce que 'git range-diff' ?", a: "Comparer deux ranges de commits (rebase comparison)",b: "Comparer des fichiers",c: "Comparer des branches",d: "Comparer des tags", ans: "a" },
      { q: "Quel est le role de 'git log --topo-order' ?", a: "Afficher les commits en ordre topologique",b: "Trier les commits",c: "Filtrer les commits",d: "Grouper les commits", ans: "a" },
      { q: "Qu'est-ce que le 'pack-objects' avec --delta-isolation ?", a: "Isoler les deltas de packing pour l'integrite",b: "Isoler les objets",c: "Isoler les branches",d: "Isoler les commits", ans: "a" },
      { q: "Quel est le role de 'git send-email' ?", a: "Envoyer des patches par email (workflow email)",b: "Envoyer des fichiers",c: "Envoyer des commits",d: "Envoyer des branches", ans: "a" },
    ],
  },
  PHP: {
    easy: [
      { q: "Comment s'ecrit une balise PHP ?", a: "<?php ?>", b: "<% %>", c: "<script>",d: "<?= ?>", ans: "a" },
      { q: "Comment affiche-t-on du texte ?", a: "echo", b: "print", c: "display",d: "say", ans: "a" },
      { q: "Comment declare-t-on une variable ?", a: "$variable", b: "variable", c: "@variable",d: "#variable", ans: "a" },
      { q: "Quel CMS est written en PHP ?", a: "WordPress", b: "Drupal", c: "Joomla",d: "Tous", ans: "d" },
      { q: "Comment commence-t-on un script PHP ?", a: "<?php", b: "<php>", c: "<script php>",d: "!php", ans: "a" },
      { q: "Quel est l'extension d'un fichier PHP ?", a: ".php", b: ".ph", c: ".phtml",d: "a et c", ans: "d" },
      { q: "Comment cree-t-on un tableau ?", a: "$arr = []", b: "$arr = array()", c: "a et b",d: "new Array()", ans: "c" },
      { q: "Comment teste-t-on une condition ?", a: "if/else", b: "when/unless", c: "case/when",d: "match/select", ans: "a" },
      { q: "Quel operateur compare la valeur et le type ?", a: "===", b: "==", c: "=",d: "<>", ans: "a" },
      { q: "Comment commente-t-on sur une ligne ?", a: "// ou #", b: "--", c: "/*",d: ";", ans: "a" },
    ],
    medium: [
      { q: "Qu'est-ce qu'une fonction PHP ?", a: "function maFunc() {}", b: "def maFunc()", c: "func maFunc()",d: "fn maFunc()", ans: "a" },
      { q: "Quelle superglobale contient les variables GET ?", a: "$_GET", b: "$_REQUEST", c: "$_QUERY",d: "$GET", ans: "a" },
      { q: "Qu'est-ce qu'un namespace en PHP ?", a: "Regrouper les classes/fonctions",b: "Un module",c: "Un package",d: "Un repertoire", ans: "a" },
      { q: "Quel operateur fusionne deux tableaux ?", a: "+ ou array_merge()", b: "merge()", c: "concat()",d: "union()", ans: "a" },
      { q: "Qu'est-ce qu'un trait en PHP ?", a: "Mecanisme de reutilisation de code horizontal",b: "Un type de classe",c: "Un design pattern",d: "Un module", ans: "a" },
      { q: "Quelle methode compte les elements d'un tableau ?", a: "count()", b: "length()", c: "size()",d: "countElements()", ans: "a" },
      { q: "Quel mot-cle herite d'une classe ?", a: "extends", b: "implements", c: "uses",d: "inherits", ans: "a" },
      { q: "Comment cree-t-on une constante ?", a: "define()", b: "const", c: "a et b",d: "static", ans: "c" },
      { q: "Quelle fonction parse du JSON ?", a: "json_decode()", b: "json_parse()", c: "decode_json()",d: "parse_json()", ans: "a" },
      { q: "Comment inclure un fichier PHP ?", a: "include/require", b: "import", c: "use",d: "load", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce qu'un autoloader en PHP ?", a: "Charge automatiquement les classes quand elles sont utilisees",b: "Un type de classe",c: "Un module",d: "Un pattern", ans: "a" },
      { q: "Quelle est la difference entre include et require ?", a: "require arrete si absent, include continue",b: "Identiques",c: "include est plus sur",d: "require est optionnel", ans: "a" },
      { q: "Qu'est-ce qu'un PSR en PHP ?", a: "Standard de codage (PHP Standards Recommendations)",b: "Un package",c: "Un framework",d: "Un protocole", ans: "a" },
      { q: "Quel est le role de Composer ?", a: "Gestionnaire de dependances PHP",b: "Un framework",c: "Un CMS",d: "Un serveur", ans: "a" },
      { q: "Qu'est-ce qu'un type union en PHP 8.0 ?", a: "Un parametre/retour qui accepte plusieurs types",b: "Un tableau de types",c: "Un type intersection",d: "Un type any", ans: "a" },
      { q: "Quel est le role du match expression (PHP 8.0) ?", a: "Remplace switch avec correspondance stricte",b: "Une comparaison",c: "Un pattern",d: "Un filtre", ans: "a" },
      { q: "Qu'est-ce que le nullsafe operator (?->) en PHP 8.0 ?", a: "Appel de methode null-safe (propage le null)",b: "Operateur de null check",c: "Un cast",d: "Un type", ans: "a" },
      { q: "Quel est le role de named arguments (PHP 8.0) ?", a: "Passer des arguments par nom au lieu de position",b: "Nommer les variables",c: "Nommage les fonctions",d: "Alias de parametres", ans: "a" },
      { q: "Qu'est-ce qu'un readonly property (PHP 8.1) ?", a: "Propriete initialisee une seule fois",b: "Propriete privee",c: "Propriete cachee",d: "Propriete constante", ans: "a" },
      { q: "Quel est le role de Fiber en PHP 8.1 ?", a: "Concurrence cooperative (threads leger)",b: "Un thread",c: "Un processus",d: "Un worker", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce qu'un enum en PHP 8.1 ?", a: "Type avec des valeurs fixes (backed ou pure)",b: "Un type de tableau",c: "Une constante",d: "Un design pattern", ans: "a" },
      { q: "Quel est le role de intersection types (PHP 8.1) ?", a: "Un type qui implemente plusieurs interfaces",b: "Croiser les types",c: "Fusionner les types",d: "Filtrer les types", ans: "a" },
      { q: "Qu'est-ce qu'un first class callable (PHP 8.1) ?", a: "Syntaxe pour referencer une fonction comme callable",b: "Un type de fonction",c: "Un closure",d: "Un callback", ans: "a" },
      { q: "Quel est le role de fibers en PHP ?", a: "Taches cooperatives avec suspension/rendu",b: "Gestion des threads",c: "Parallel processing",d: "Async IO", ans: "a" },
      { q: "Qu'est-ce qu'un readonly class (PHP 8.2) ?", a: "Classe dont toutes les proprietes sont readonly",b: "Classe privee",c: "Classe abstraite",d: "Classe finale", ans: "a" },
      { q: "Quel est le role de DNF types (PHP 8.2) ?", a: "Types disjonctifs normaux ((A&B)|C)",b: "Types dynamiques",c: "Types flexibles",d: "Types generiques", ans: "a" },
      { q: "Qu'est-ce qu'un dynamic property (PHP 8.2) ?", a: "Propriete creee dynamiquement (deprecated)",b: "Propriete statique",c: "Propriete finale",d: "Propriete readonly", ans: "a" },
      { q: "Quel est le role de 'json_validate() (PHP 8.3) ?", a: "Valider une chaine JSON sans la decoder",b: "Valider le schema",c: "Decoder le JSON",d: "Encoder le JSON", ans: "a" },
      { q: "Qu'est-ce qu'un typed class constants (PHP 8.3) ?", a: "Constantes de classe avec type declare",b: "Constantes typées",c: "Constantes dynamiques",d: "Constantes readonly", ans: "a" },
      { q: "Quel est le role de 'Override' attribute (PHP 8.3) ?", a: "Marquer explicitement une methode qui surcharge un parent",b: "Remplacer un attribut",c: "Cacher une methode",d: "Modifier une constante", ans: "a" },
    ],
    master: [
      { q: "Quel est le role de 'phpdbg' ?", a: "Debugger et profiler PHP en ligne de commande",b: "Un error handler",c: "Un logger",d: "Un cache", ans: "a" },
      { q: "Qu'est-ce qu'un opcache en PHP ?", a: "Cache du bytecode compile pour accelerer l'execution",b: "Un cache HTTP",c: "Un cache de base de donnees",d: "Un cache de fichiers", ans: "a" },
      { q: "Quel est le role de PHP-FPM ?", a: "FastCGI Process Manager pour gerer les processus PHP",b: "Un framework",c: "Un ORM",d: "Un template engine", ans: "a" },
      { q: "Qu'est-ce que le 'JIT compiler' en PHP 8 ?", a: "Compilateur Just-In-Time pour accelerer le code",b: "Un compilaire statique",c: "Un interpreteur",d: "Un decompiler", ans: "a" },
      { q: "Quel est le role de 'FFI' en PHP ?", a: "Interface pour appeler du code C/autres langages",b: "Une interface utilisateur",c: "Un framework",d: "Un ORM", ans: "a" },
      { q: "Qu'est-ce qu'un 'preloading' en PHP 7.4 ?", a: "Charger des scripts au demarrage de FPM",b: "Pre-charger des donnees",c: "Pre-compiler du code",d: "Pre-executer des tests", ans: "a" },
      { q: "Quel est le role de 'Swoole' ou 'Roadrunner' ?", a: "Serveurs HTTP asynchrones pour PHP",b: "Des frameworks",c: "Des ORM",d: "Des CMS", ans: "a" },
      { q: "Qu'est-ce qu'un 'attribute' en PHP 8 ?", a: "Metadonnees declaratives sur les classes/methodes/proprietes",b: "Un decorateur",c: "Un type",d: "Un design pattern", ans: "a" },
      { q: "Quel est le role de 'PHP-Parser' (nikic) ?", a: "Parser le code PHP en AST (Abstract Syntax Tree)",b: "Parser du HTML",c: "Parser du SQL",d: "Parser du JSON", ans: "a" },
      { q: "Qu'est-ce qu'un 'extension' PHP en C ?", a: "Module compile en C pour etendre PHP nativement",b: "Un package",c: "Un framework",d: "Un plugin", ans: "a" },
    ],
  },
  Rust: {
    easy: [
      { q: "Quel mot-cle declare une variable immuable ?", a: "let", b: "const", c: "var",d: "static", ans: "a" },
      { q: "Comment rend-on une variable mutable ?", a: "let mut", b: "let var", c: "mutable let",d: "var let", ans: "a" },
      { q: "Quel est le systeme de gestion de packages Rust ?", a: "Cargo", b: "Rustup", c: "Crates",d: "Pkg", ans: "a" },
      { q: "Comment affiche-t-on dans la console ?", a: "println!()", b: "print()", c: "echo()",d: "log()", ans: "a" },
      { q: "Quel est le fichier de config Cargo ?", a: "Cargo.toml", b: "rust.config", c: "Cargo.json",d: "config.toml", ans: "a" },
      { q: "Comment declare-t-on une fonction ?", a: "fn()", b: "func()", c: "def()",d: "function()", ans: "a" },
      { q: "Quel type represente un texte ?", a: "&str", b: "String", c: "text",d: "char", ans: "b" },
      { q: "Quel est le type entier par defaut ?", a: "i32", b: "i64", c: "int",d: "u32", ans: "a" },
      { q: "Comment cree-t-on un commentaire sur une ligne ?", a: "//", b: "#", c: "--",d: "/*", ans: "a" },
      { q: "Quel mot-cle definit une constante ?", a: "const", b: "let", c: "static",d: "define", ans: "a" },
    ],
    medium: [
      { q: "Qu'est-ce que le 'ownership' en Rust ?", a: "Chaque valeur a un unique proprietaire",b: "Un type d'heritage",c: "Un pattern de design",d: "Un module", ans: "a" },
      { q: "Qu'est-ce que le borrow checker ?", a: "Verifier les regles d'emprunt a la compilation",b: "Un testeur",c: "Un linter",d: "Un formatteur", ans: "a" },
      { q: "Quel mot-cle cree un emprunt immutable ?", a: "&", b: "&mut", c: "*",d: "@", ans: "a" },
      { q: "Quel mot-cle cree un emprunt mutable ?", a: "&mut", b: "&", c: "mut",d: "ref", ans: "a" },
      { q: "Qu'est-ce qu'un trait en Rust ?", a: "Ensemble de methodes partagees (comme une interface)",b: "Un type",c: "Une struct",d: "Un module", ans: "a" },
      { q: "Quel est le resultat d'un crash de compilation Rust ?", a: "Un message d'erreur compile", b: "Une exception runtime",c: "Un crash silencieux",d: "Un warning", ans: "a" },
      { q: "Qu'est-ce qu'un enum en Rust ?", a: "Type avec des variantes nommees",b: "Un type numerique",c: "Un tableau",d: "Une liste", ans: "a" },
      { q: "Quel mot-cle gère les erreurs sans panic ?", a: "Result<T, E>", b: "Option<T>", c: "try/catch",d: "error", ans: "a" },
      { q: "Qu'est-ce qu'un pattern match (match) ?", a: "Correspondance exhaustive sur des patterns",b: "Un switch",c: "Un if/else",d: "Un test", ans: "a" },
      { q: "Quel est le role de 'unwrap()' ?", a: "Extraire la valeur ou panic si None/Err",b: "Deballer un package",c: "Initialiser",d: "Nettoyer", ans: "a" },
    ],
    hard: [
      { q: "Qu'est-ce qu'un lifetime en Rust ?", a: "Duree de vie d'une reference (eviter le dangling)",b: "Une constante temporelle",c: "Un timer",d: "Un delai", ans: "a" },
      { q: "Quel est le role de 'impl Trait' ?", a: "Implementer un trait pour un type",b: "Implementer une classe",c: "Implementer une fonction",d: "Implementer un module", ans: "a" },
      { q: "Qu'est-ce qu'un 'move closure' en Rust ?", a: "Closure qui prend ownership des variables capturees",b: "Closure rapide",c: "Closure externe",d: "Closure globale", ans: "a" },
      { q: "Quel est le role de 'Arc<Mutex<T>>' ?", a: "Partage thread-safe avec emprunt mutable",b: "Un arc-en-ciel",c: "Un mutex simple",d: "Un thread", ans: "a" },
      { q: "Qu'est-ce que le 'deref coercion' en Rust ?", a: "Conversion automatique via Deref (String->&str)",b: "Dereferencer un pointeur",c: "Convertir un type",d: "Caster un type", ans: "a" },
      { q: "Quel est le role de 'Box<T>' ?", a: "Allouer sur le heap une seule valeur",b: "Une boite de stockage",c: "Un type primitif",d: "Un conteneur", ans: "a" },
      { q: "Qu'est-ce qu'un 'trait object' (dyn Trait) ?", a: "Dispatch dynamique (vtable) pour les traits",b: "Un objet concrete",c: "Un type statique",d: "Un module", ans: "a" },
      { q: "Quel est le role de 'Pin<P>' en Rust ?", a: "Empecher le deplacement d'un pointeur (async)",b: "Epingler un thread",c: "Fixer un pointeur",d: "Bloquer un accès", ans: "a" },
      { q: "Qu'est-ce que le 'async/await' en Rust ?", a: "Programmation asynchrone cooperative",b: "Multithreading",c: "Parallel processing",d: "Thread pooling", ans: "a" },
      { q: "Quel est le role de 'PhantomData<T>' ?", a: "Marqueur de type sans allocation reelle",b: "Donnee fantome",c: "Type optionnel",d: "Type cache", ans: "a" },
    ],
    expert: [
      { q: "Qu'est-ce que le 'specialization' en Rust (nightly) ?", a: "Specialiser les implementations de traits",b: "Specialiser les types",c: "Specialiser les fonctions",d: "Specialiser les modules", ans: "a" },
      { q: "Quel est le role de 'const generics' ?", a: "Parametres de type const (Vec<T, N>)",b: "Constantes generiques",c: "Types const",d: "Generiques const", ans: "a" },
      { q: "Qu'est-ce que le 'GAT' (Generic Associated Types) ?", a: "Types associes generiques (Item<'a>)",b: "Types associes globaux",c: "Types associes generaux",d: "Types generiques associes", ans: "a" },
      { q: "Quel est le role de 'Transmute' ?", a: "Convertir brute un type en un autre (unsafe)",b: "Transmettre des donnees",c: "Transformer un type",d: "Traduire du code", ans: "a" },
      { q: "Qu'est-ce que le 'MIR' en Rust ?", a: "Mid-level Intermediate Representation (IR du compilateur)",b: "Un type de donnees",c: "Un module",d: "Un pattern", ans: "a" },
      { q: "Quel est le role de 'Polonais Notation' (PN) dans le borrow checker ?", a: "Representer les emprunts comme un automate a pile",b: "Notation mathematique",c: "Syntaxe speciale",d: "Pattern de code", ans: "a" },
      { q: "Qu'est-ce que 'NLL' (Non-Lexical Lifetimes) ?", a: "Lifetimes basees sur l'utilisation reelle, pas la portee lexicale",b: "Lifetimes lexicales",c: "Lifetimes globales",d: "Lifetimes courtes", ans: "a" },
      { q: "Quel est le role de 'Stable ABI' (discussion) ?", a: "Garantir la compatibilite binaire entre versions Rust",b: "Stabiliser le langage",c: "Stabiliser les APIs",d: "Stabiliser les crates", ans: "a" },
      { q: "Qu'est-ce que le 'polonais' borrow checking dans Polonius ?", a: "Nouvel algorithme de borrow checking (remplace NLL)",b: "Un algorithme de tri",c: "Un parser",d: "Un optimizeur", ans: "a" },
      { q: "Quel est le role de 'chalk' en Rust ?", a: "Solveur de traits pour le systeme de types",b: "Un ecriture",c: "Un style",d: "Un format", ans: "a" },
    ],
    master: [
      { q: "Qu'est-ce que 'unsafe Rust' ?", a: "Activer les fonctionnalites dangereuses (pointeurs nus, etc.)",b: "Le mode securise",c: "Le mode debug",d: "Le mode release", ans: "a" },
      { q: "Quel est le role de 'no_std' en Rust ?", a: "Bibliotheca standard minimale pour embedded/embedding",b: "Pas de standard",c: "Pas de bibliotheque",d: "Pas de framework", ans: "a" },
      { q: "Qu'est-ce que le 'embedded Rust' ?", a: "Programmer des systemes embarques en Rust (no_std)",b: "Rust dans un navigateur",c: "Rust dans Node.js",d: "Rust dans Python", ans: "a" },
      { q: "Quel est le role de 'proc-macro' en Rust ?", a: "Macros qui manipulent le code (derive, attribute)",b: "Macros de procedure",c: "Macros simples",d: "Macros de compilation", ans: "a" },
      { q: "Qu'est-ce que 'serde' en Rust ?", a: "Framework de serialisation/deserialisation generique",b: "Un ORM",c: "Un framework web",d: "Un client HTTP", ans: "a" },
      { q: "Quel est le role de 'tokio' en Rust ?", a: "Runtime asynchrone pour Rust (event loop, workers)",b: "Un framework web",c: "Un ORM",d: "Un client HTTP", ans: "a" },
      { q: "Qu'est-ce que le 'zero-cost abstraction' en Rust ?", a: "Les abstractions n'ajoutent pas de cout runtime",b: "Pas de cout de compilation",c: "Pas de cout de package",d: "Pas de cout de maintenance", ans: "a" },
      { q: "Quel est le role de 'miri' en Rust ?", a: "Detecter le comportement indefini (UB) dans le code Rust",b: "Un interpreteur",c: "Un compilateur",d: "Un linter", ans: "a" },
      { q: "Qu'est-ce que 'cranelift' en Rust ?", a: "Backend de compilation (alternative a LLVM)",b: "Un framework",c: "Un ORM",d: "Un runtime", ans: "a" },
      { q: "Quel est le role de 'riir' (Rewrite It In Rust) ?", a: "Reecrire des outils/systemes existants en Rust",b: "Un package",c: "Un framework",d: "Un standard", ans: "a" },
    ],
  },
};

// Generate SQL
// 11 languages × 100 levels = 1100 questions
// easy: 1-10 & 51-60, medium: 11-20 & 61-70, hard: 21-30 & 71-80, expert: 31-40 & 81-90, master: 41-50 & 91-100

let sql = `-- Quiz Questions Seed\n-- 11 langages × 100 niveaux = 1100 questions\n\nINSERT INTO QuizQuestions (language, difficulty_level, question, option_a, option_b, option_c, option_d, correct_answer) VALUES\n`;

const tierMapping = [
  { label: 'easy', startLevel: 1 },
  { label: 'medium', startLevel: 11 },
  { label: 'hard', startLevel: 21 },
  { label: 'expert', startLevel: 31 },
  { label: 'master', startLevel: 41 },
];

const escape = (s) => s.replace(/'/g, "''");
const values = [];

for (const [lang, levels] of Object.entries(languages)) {
  for (const tier of tierMapping) {
    const questions = levels[tier.label];
    if (!questions) continue;
    for (let i = 0; i < questions.length; i++) {
      const q = questions[i];
      // First pass: levels 1-50
      const level1 = tier.startLevel + i;
      values.push(`('${escape(lang)}', ${level1}, '${escape(q.q)}', '${escape(q.a)}', '${escape(q.b)}', '${escape(q.c)}', '${escape(q.d)}', '${q.ans}')`);
      // Second pass: levels 51-100 (reuse same questions)
      const level2 = tier.startLevel + 50 + i;
      values.push(`('${escape(lang)}', ${level2}, '${escape(q.q)}', '${escape(q.a)}', '${escape(q.b)}', '${escape(q.c)}', '${escape(q.d)}', '${q.ans}')`);
    }
  }
}

sql += values.join(',\n') + ';\n';

console.log(`Generated ${values.length} questions`);
console.log(`Languages: ${Object.keys(languages).length}`);

// Write to file
const fs = require('fs');
fs.writeFileSync('/home/hachemmy/Bureau/Flem\'art/database/seeds/002_quiz_questions.sql', sql);
console.log('Written to database/seeds/002_quiz_questions.sql');
